// Code generated by ent, DO NOT EDIT.

package conversationmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldID, id))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldConversationID, v))
}

// SenderType applies equality check predicate on the "sender_type" field. It's identical to SenderTypeEQ.
func SenderType(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldSenderType, v))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldSenderID, v))
}

// MessageType applies equality check predicate on the "message_type" field. It's identical to MessageTypeEQ.
func MessageType(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldMessageType, v))
}

// ContentFormat applies equality check predicate on the "content_format" field. It's identical to ContentFormatEQ.
func ContentFormat(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldContentFormat, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldConversationID, vs...))
}

// SenderTypeEQ applies the EQ predicate on the "sender_type" field.
func SenderTypeEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldSenderType, v))
}

// SenderTypeNEQ applies the NEQ predicate on the "sender_type" field.
func SenderTypeNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldSenderType, v))
}

// SenderTypeIn applies the In predicate on the "sender_type" field.
func SenderTypeIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldSenderType, vs...))
}

// SenderTypeNotIn applies the NotIn predicate on the "sender_type" field.
func SenderTypeNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldSenderType, vs...))
}

// SenderTypeGT applies the GT predicate on the "sender_type" field.
func SenderTypeGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldSenderType, v))
}

// SenderTypeGTE applies the GTE predicate on the "sender_type" field.
func SenderTypeGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldSenderType, v))
}

// SenderTypeLT applies the LT predicate on the "sender_type" field.
func SenderTypeLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldSenderType, v))
}

// SenderTypeLTE applies the LTE predicate on the "sender_type" field.
func SenderTypeLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldSenderType, v))
}

// SenderTypeContains applies the Contains predicate on the "sender_type" field.
func SenderTypeContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldSenderType, v))
}

// SenderTypeHasPrefix applies the HasPrefix predicate on the "sender_type" field.
func SenderTypeHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldSenderType, v))
}

// SenderTypeHasSuffix applies the HasSuffix predicate on the "sender_type" field.
func SenderTypeHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldSenderType, v))
}

// SenderTypeEqualFold applies the EqualFold predicate on the "sender_type" field.
func SenderTypeEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldSenderType, v))
}

// SenderTypeContainsFold applies the ContainsFold predicate on the "sender_type" field.
func SenderTypeContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldSenderType, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...int64) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDIsNil applies the IsNil predicate on the "sender_id" field.
func SenderIDIsNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIsNull(FieldSenderID))
}

// SenderIDNotNil applies the NotNil predicate on the "sender_id" field.
func SenderIDNotNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotNull(FieldSenderID))
}

// MessageTypeEQ applies the EQ predicate on the "message_type" field.
func MessageTypeEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldMessageType, v))
}

// MessageTypeNEQ applies the NEQ predicate on the "message_type" field.
func MessageTypeNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldMessageType, v))
}

// MessageTypeIn applies the In predicate on the "message_type" field.
func MessageTypeIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldMessageType, vs...))
}

// MessageTypeNotIn applies the NotIn predicate on the "message_type" field.
func MessageTypeNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldMessageType, vs...))
}

// MessageTypeGT applies the GT predicate on the "message_type" field.
func MessageTypeGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldMessageType, v))
}

// MessageTypeGTE applies the GTE predicate on the "message_type" field.
func MessageTypeGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldMessageType, v))
}

// MessageTypeLT applies the LT predicate on the "message_type" field.
func MessageTypeLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldMessageType, v))
}

// MessageTypeLTE applies the LTE predicate on the "message_type" field.
func MessageTypeLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldMessageType, v))
}

// MessageTypeContains applies the Contains predicate on the "message_type" field.
func MessageTypeContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldMessageType, v))
}

// MessageTypeHasPrefix applies the HasPrefix predicate on the "message_type" field.
func MessageTypeHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldMessageType, v))
}

// MessageTypeHasSuffix applies the HasSuffix predicate on the "message_type" field.
func MessageTypeHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldMessageType, v))
}

// MessageTypeEqualFold applies the EqualFold predicate on the "message_type" field.
func MessageTypeEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldMessageType, v))
}

// MessageTypeContainsFold applies the ContainsFold predicate on the "message_type" field.
func MessageTypeContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldMessageType, v))
}

// ContentFormatEQ applies the EQ predicate on the "content_format" field.
func ContentFormatEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldContentFormat, v))
}

// ContentFormatNEQ applies the NEQ predicate on the "content_format" field.
func ContentFormatNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldContentFormat, v))
}

// ContentFormatIn applies the In predicate on the "content_format" field.
func ContentFormatIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldContentFormat, vs...))
}

// ContentFormatNotIn applies the NotIn predicate on the "content_format" field.
func ContentFormatNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldContentFormat, vs...))
}

// ContentFormatGT applies the GT predicate on the "content_format" field.
func ContentFormatGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldContentFormat, v))
}

// ContentFormatGTE applies the GTE predicate on the "content_format" field.
func ContentFormatGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldContentFormat, v))
}

// ContentFormatLT applies the LT predicate on the "content_format" field.
func ContentFormatLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldContentFormat, v))
}

// ContentFormatLTE applies the LTE predicate on the "content_format" field.
func ContentFormatLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldContentFormat, v))
}

// ContentFormatContains applies the Contains predicate on the "content_format" field.
func ContentFormatContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldContentFormat, v))
}

// ContentFormatHasPrefix applies the HasPrefix predicate on the "content_format" field.
func ContentFormatHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldContentFormat, v))
}

// ContentFormatHasSuffix applies the HasSuffix predicate on the "content_format" field.
func ContentFormatHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldContentFormat, v))
}

// ContentFormatEqualFold applies the EqualFold predicate on the "content_format" field.
func ContentFormatEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldContentFormat, v))
}

// ContentFormatContainsFold applies the ContainsFold predicate on the "content_format" field.
func ContentFormatContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldContentFormat, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldContainsFold(FieldContent, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasConversation applies the HasEdge predicate on the "conversation" edge.
func HasConversation() predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConversationTable, ConversationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConversationWith applies the HasEdge predicate on the "conversation" edge with a given conditions (other predicates).
func HasConversationWith(preds ...predicate.Conversation) predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := newConversationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSender applies the HasEdge predicate on the "sender" edge.
func HasSender() predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SenderTable, SenderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSenderWith applies the HasEdge predicate on the "sender" edge with a given conditions (other predicates).
func HasSenderWith(preds ...predicate.User) predicate.ConversationMessage {
	return predicate.ConversationMessage(func(s *sql.Selector) {
		step := newSenderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConversationMessage) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConversationMessage) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConversationMessage) predicate.ConversationMessage {
	return predicate.ConversationMessage(sql.NotPredicates(p))
}
