// Code generated by ent, DO NOT EDIT.

package conversation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUserID, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSubject, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldStatus, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldKind, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldPriority, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldType, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSource, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSourceID, v))
}

// ReferencedNoticeID applies equality check predicate on the "referenced_notice_id" field. It's identical to ReferencedNoticeIDEQ.
func ReferencedNoticeID(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldReferencedNoticeID, v))
}

// AssignedAdminID applies equality check predicate on the "assigned_admin_id" field. It's identical to AssignedAdminIDEQ.
func AssignedAdminID(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldAssignedAdminID, v))
}

// LastMessageID applies equality check predicate on the "last_message_id" field. It's identical to LastMessageIDEQ.
func LastMessageID(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastMessageID, v))
}

// LastMessageSenderType applies equality check predicate on the "last_message_sender_type" field. It's identical to LastMessageSenderTypeEQ.
func LastMessageSenderType(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastMessageSenderType, v))
}

// LastMessageExcerpt applies equality check predicate on the "last_message_excerpt" field. It's identical to LastMessageExcerptEQ.
func LastMessageExcerpt(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastMessageExcerpt, v))
}

// LastMessageAt applies equality check predicate on the "last_message_at" field. It's identical to LastMessageAtEQ.
func LastMessageAt(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastMessageAt, v))
}

// UserLastReadMessageID applies equality check predicate on the "user_last_read_message_id" field. It's identical to UserLastReadMessageIDEQ.
func UserLastReadMessageID(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUserLastReadMessageID, v))
}

// UserLastReadAt applies equality check predicate on the "user_last_read_at" field. It's identical to UserLastReadAtEQ.
func UserLastReadAt(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUserLastReadAt, v))
}

// AdminLastReadMessageID applies equality check predicate on the "admin_last_read_message_id" field. It's identical to AdminLastReadMessageIDEQ.
func AdminLastReadMessageID(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldAdminLastReadMessageID, v))
}

// AdminLastReadAt applies equality check predicate on the "admin_last_read_at" field. It's identical to AdminLastReadAtEQ.
func AdminLastReadAt(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldAdminLastReadAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldUserID, vs...))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldSubject, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldStatus, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldKind, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldPriority, v))
}

// PriorityContains applies the Contains predicate on the "priority" field.
func PriorityContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldPriority, v))
}

// PriorityHasPrefix applies the HasPrefix predicate on the "priority" field.
func PriorityHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldPriority, v))
}

// PriorityHasSuffix applies the HasSuffix predicate on the "priority" field.
func PriorityHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldPriority, v))
}

// PriorityEqualFold applies the EqualFold predicate on the "priority" field.
func PriorityEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldPriority, v))
}

// PriorityContainsFold applies the ContainsFold predicate on the "priority" field.
func PriorityContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldPriority, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldType, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldSource, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDContains applies the Contains predicate on the "source_id" field.
func SourceIDContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldSourceID, v))
}

// SourceIDHasPrefix applies the HasPrefix predicate on the "source_id" field.
func SourceIDHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldSourceID, v))
}

// SourceIDHasSuffix applies the HasSuffix predicate on the "source_id" field.
func SourceIDHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldSourceID, v))
}

// SourceIDEqualFold applies the EqualFold predicate on the "source_id" field.
func SourceIDEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldSourceID, v))
}

// SourceIDContainsFold applies the ContainsFold predicate on the "source_id" field.
func SourceIDContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldSourceID, v))
}

// ReferencedNoticeIDEQ applies the EQ predicate on the "referenced_notice_id" field.
func ReferencedNoticeIDEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldReferencedNoticeID, v))
}

// ReferencedNoticeIDNEQ applies the NEQ predicate on the "referenced_notice_id" field.
func ReferencedNoticeIDNEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldReferencedNoticeID, v))
}

// ReferencedNoticeIDIn applies the In predicate on the "referenced_notice_id" field.
func ReferencedNoticeIDIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldReferencedNoticeID, vs...))
}

// ReferencedNoticeIDNotIn applies the NotIn predicate on the "referenced_notice_id" field.
func ReferencedNoticeIDNotIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldReferencedNoticeID, vs...))
}

// ReferencedNoticeIDIsNil applies the IsNil predicate on the "referenced_notice_id" field.
func ReferencedNoticeIDIsNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldIsNull(FieldReferencedNoticeID))
}

// ReferencedNoticeIDNotNil applies the NotNil predicate on the "referenced_notice_id" field.
func ReferencedNoticeIDNotNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldNotNull(FieldReferencedNoticeID))
}

// AssignedAdminIDEQ applies the EQ predicate on the "assigned_admin_id" field.
func AssignedAdminIDEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldAssignedAdminID, v))
}

// AssignedAdminIDNEQ applies the NEQ predicate on the "assigned_admin_id" field.
func AssignedAdminIDNEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldAssignedAdminID, v))
}

// AssignedAdminIDIn applies the In predicate on the "assigned_admin_id" field.
func AssignedAdminIDIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldAssignedAdminID, vs...))
}

// AssignedAdminIDNotIn applies the NotIn predicate on the "assigned_admin_id" field.
func AssignedAdminIDNotIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldAssignedAdminID, vs...))
}

// AssignedAdminIDIsNil applies the IsNil predicate on the "assigned_admin_id" field.
func AssignedAdminIDIsNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldIsNull(FieldAssignedAdminID))
}

// AssignedAdminIDNotNil applies the NotNil predicate on the "assigned_admin_id" field.
func AssignedAdminIDNotNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldNotNull(FieldAssignedAdminID))
}

// LastMessageIDEQ applies the EQ predicate on the "last_message_id" field.
func LastMessageIDEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastMessageID, v))
}

// LastMessageIDNEQ applies the NEQ predicate on the "last_message_id" field.
func LastMessageIDNEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldLastMessageID, v))
}

// LastMessageIDIn applies the In predicate on the "last_message_id" field.
func LastMessageIDIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldLastMessageID, vs...))
}

// LastMessageIDNotIn applies the NotIn predicate on the "last_message_id" field.
func LastMessageIDNotIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldLastMessageID, vs...))
}

// LastMessageIDGT applies the GT predicate on the "last_message_id" field.
func LastMessageIDGT(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldLastMessageID, v))
}

// LastMessageIDGTE applies the GTE predicate on the "last_message_id" field.
func LastMessageIDGTE(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldLastMessageID, v))
}

// LastMessageIDLT applies the LT predicate on the "last_message_id" field.
func LastMessageIDLT(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldLastMessageID, v))
}

// LastMessageIDLTE applies the LTE predicate on the "last_message_id" field.
func LastMessageIDLTE(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldLastMessageID, v))
}

// LastMessageIDIsNil applies the IsNil predicate on the "last_message_id" field.
func LastMessageIDIsNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldIsNull(FieldLastMessageID))
}

// LastMessageIDNotNil applies the NotNil predicate on the "last_message_id" field.
func LastMessageIDNotNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldNotNull(FieldLastMessageID))
}

// LastMessageSenderTypeEQ applies the EQ predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeNEQ applies the NEQ predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeIn applies the In predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldLastMessageSenderType, vs...))
}

// LastMessageSenderTypeNotIn applies the NotIn predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldLastMessageSenderType, vs...))
}

// LastMessageSenderTypeGT applies the GT predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeGTE applies the GTE predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeLT applies the LT predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeLTE applies the LTE predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeContains applies the Contains predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeHasPrefix applies the HasPrefix predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeHasSuffix applies the HasSuffix predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeEqualFold applies the EqualFold predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldLastMessageSenderType, v))
}

// LastMessageSenderTypeContainsFold applies the ContainsFold predicate on the "last_message_sender_type" field.
func LastMessageSenderTypeContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldLastMessageSenderType, v))
}

// LastMessageExcerptEQ applies the EQ predicate on the "last_message_excerpt" field.
func LastMessageExcerptEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptNEQ applies the NEQ predicate on the "last_message_excerpt" field.
func LastMessageExcerptNEQ(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptIn applies the In predicate on the "last_message_excerpt" field.
func LastMessageExcerptIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldLastMessageExcerpt, vs...))
}

// LastMessageExcerptNotIn applies the NotIn predicate on the "last_message_excerpt" field.
func LastMessageExcerptNotIn(vs ...string) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldLastMessageExcerpt, vs...))
}

// LastMessageExcerptGT applies the GT predicate on the "last_message_excerpt" field.
func LastMessageExcerptGT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptGTE applies the GTE predicate on the "last_message_excerpt" field.
func LastMessageExcerptGTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptLT applies the LT predicate on the "last_message_excerpt" field.
func LastMessageExcerptLT(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptLTE applies the LTE predicate on the "last_message_excerpt" field.
func LastMessageExcerptLTE(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptContains applies the Contains predicate on the "last_message_excerpt" field.
func LastMessageExcerptContains(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContains(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptHasPrefix applies the HasPrefix predicate on the "last_message_excerpt" field.
func LastMessageExcerptHasPrefix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasPrefix(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptHasSuffix applies the HasSuffix predicate on the "last_message_excerpt" field.
func LastMessageExcerptHasSuffix(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldHasSuffix(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptEqualFold applies the EqualFold predicate on the "last_message_excerpt" field.
func LastMessageExcerptEqualFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldEqualFold(FieldLastMessageExcerpt, v))
}

// LastMessageExcerptContainsFold applies the ContainsFold predicate on the "last_message_excerpt" field.
func LastMessageExcerptContainsFold(v string) predicate.Conversation {
	return predicate.Conversation(sql.FieldContainsFold(FieldLastMessageExcerpt, v))
}

// LastMessageAtEQ applies the EQ predicate on the "last_message_at" field.
func LastMessageAtEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldLastMessageAt, v))
}

// LastMessageAtNEQ applies the NEQ predicate on the "last_message_at" field.
func LastMessageAtNEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldLastMessageAt, v))
}

// LastMessageAtIn applies the In predicate on the "last_message_at" field.
func LastMessageAtIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldLastMessageAt, vs...))
}

// LastMessageAtNotIn applies the NotIn predicate on the "last_message_at" field.
func LastMessageAtNotIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldLastMessageAt, vs...))
}

// LastMessageAtGT applies the GT predicate on the "last_message_at" field.
func LastMessageAtGT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldLastMessageAt, v))
}

// LastMessageAtGTE applies the GTE predicate on the "last_message_at" field.
func LastMessageAtGTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldLastMessageAt, v))
}

// LastMessageAtLT applies the LT predicate on the "last_message_at" field.
func LastMessageAtLT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldLastMessageAt, v))
}

// LastMessageAtLTE applies the LTE predicate on the "last_message_at" field.
func LastMessageAtLTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldLastMessageAt, v))
}

// UserLastReadMessageIDEQ applies the EQ predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUserLastReadMessageID, v))
}

// UserLastReadMessageIDNEQ applies the NEQ predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDNEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldUserLastReadMessageID, v))
}

// UserLastReadMessageIDIn applies the In predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldUserLastReadMessageID, vs...))
}

// UserLastReadMessageIDNotIn applies the NotIn predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDNotIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldUserLastReadMessageID, vs...))
}

// UserLastReadMessageIDGT applies the GT predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDGT(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldUserLastReadMessageID, v))
}

// UserLastReadMessageIDGTE applies the GTE predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDGTE(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldUserLastReadMessageID, v))
}

// UserLastReadMessageIDLT applies the LT predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDLT(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldUserLastReadMessageID, v))
}

// UserLastReadMessageIDLTE applies the LTE predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDLTE(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldUserLastReadMessageID, v))
}

// UserLastReadMessageIDIsNil applies the IsNil predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDIsNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldIsNull(FieldUserLastReadMessageID))
}

// UserLastReadMessageIDNotNil applies the NotNil predicate on the "user_last_read_message_id" field.
func UserLastReadMessageIDNotNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldNotNull(FieldUserLastReadMessageID))
}

// UserLastReadAtEQ applies the EQ predicate on the "user_last_read_at" field.
func UserLastReadAtEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldUserLastReadAt, v))
}

// UserLastReadAtNEQ applies the NEQ predicate on the "user_last_read_at" field.
func UserLastReadAtNEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldUserLastReadAt, v))
}

// UserLastReadAtIn applies the In predicate on the "user_last_read_at" field.
func UserLastReadAtIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldUserLastReadAt, vs...))
}

// UserLastReadAtNotIn applies the NotIn predicate on the "user_last_read_at" field.
func UserLastReadAtNotIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldUserLastReadAt, vs...))
}

// UserLastReadAtGT applies the GT predicate on the "user_last_read_at" field.
func UserLastReadAtGT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldUserLastReadAt, v))
}

// UserLastReadAtGTE applies the GTE predicate on the "user_last_read_at" field.
func UserLastReadAtGTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldUserLastReadAt, v))
}

// UserLastReadAtLT applies the LT predicate on the "user_last_read_at" field.
func UserLastReadAtLT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldUserLastReadAt, v))
}

// UserLastReadAtLTE applies the LTE predicate on the "user_last_read_at" field.
func UserLastReadAtLTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldUserLastReadAt, v))
}

// UserLastReadAtIsNil applies the IsNil predicate on the "user_last_read_at" field.
func UserLastReadAtIsNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldIsNull(FieldUserLastReadAt))
}

// UserLastReadAtNotNil applies the NotNil predicate on the "user_last_read_at" field.
func UserLastReadAtNotNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldNotNull(FieldUserLastReadAt))
}

// AdminLastReadMessageIDEQ applies the EQ predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldAdminLastReadMessageID, v))
}

// AdminLastReadMessageIDNEQ applies the NEQ predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDNEQ(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldAdminLastReadMessageID, v))
}

// AdminLastReadMessageIDIn applies the In predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldAdminLastReadMessageID, vs...))
}

// AdminLastReadMessageIDNotIn applies the NotIn predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDNotIn(vs ...int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldAdminLastReadMessageID, vs...))
}

// AdminLastReadMessageIDGT applies the GT predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDGT(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldAdminLastReadMessageID, v))
}

// AdminLastReadMessageIDGTE applies the GTE predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDGTE(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldAdminLastReadMessageID, v))
}

// AdminLastReadMessageIDLT applies the LT predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDLT(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldAdminLastReadMessageID, v))
}

// AdminLastReadMessageIDLTE applies the LTE predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDLTE(v int64) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldAdminLastReadMessageID, v))
}

// AdminLastReadMessageIDIsNil applies the IsNil predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDIsNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldIsNull(FieldAdminLastReadMessageID))
}

// AdminLastReadMessageIDNotNil applies the NotNil predicate on the "admin_last_read_message_id" field.
func AdminLastReadMessageIDNotNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldNotNull(FieldAdminLastReadMessageID))
}

// AdminLastReadAtEQ applies the EQ predicate on the "admin_last_read_at" field.
func AdminLastReadAtEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldEQ(FieldAdminLastReadAt, v))
}

// AdminLastReadAtNEQ applies the NEQ predicate on the "admin_last_read_at" field.
func AdminLastReadAtNEQ(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNEQ(FieldAdminLastReadAt, v))
}

// AdminLastReadAtIn applies the In predicate on the "admin_last_read_at" field.
func AdminLastReadAtIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldIn(FieldAdminLastReadAt, vs...))
}

// AdminLastReadAtNotIn applies the NotIn predicate on the "admin_last_read_at" field.
func AdminLastReadAtNotIn(vs ...time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldNotIn(FieldAdminLastReadAt, vs...))
}

// AdminLastReadAtGT applies the GT predicate on the "admin_last_read_at" field.
func AdminLastReadAtGT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGT(FieldAdminLastReadAt, v))
}

// AdminLastReadAtGTE applies the GTE predicate on the "admin_last_read_at" field.
func AdminLastReadAtGTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldGTE(FieldAdminLastReadAt, v))
}

// AdminLastReadAtLT applies the LT predicate on the "admin_last_read_at" field.
func AdminLastReadAtLT(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLT(FieldAdminLastReadAt, v))
}

// AdminLastReadAtLTE applies the LTE predicate on the "admin_last_read_at" field.
func AdminLastReadAtLTE(v time.Time) predicate.Conversation {
	return predicate.Conversation(sql.FieldLTE(FieldAdminLastReadAt, v))
}

// AdminLastReadAtIsNil applies the IsNil predicate on the "admin_last_read_at" field.
func AdminLastReadAtIsNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldIsNull(FieldAdminLastReadAt))
}

// AdminLastReadAtNotNil applies the NotNil predicate on the "admin_last_read_at" field.
func AdminLastReadAtNotNil() predicate.Conversation {
	return predicate.Conversation(sql.FieldNotNull(FieldAdminLastReadAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedAdmin applies the HasEdge predicate on the "assigned_admin" edge.
func HasAssignedAdmin() predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssignedAdminTable, AssignedAdminColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedAdminWith applies the HasEdge predicate on the "assigned_admin" edge with a given conditions (other predicates).
func HasAssignedAdminWith(preds ...predicate.User) predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := newAssignedAdminStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReferencedNotice applies the HasEdge predicate on the "referenced_notice" edge.
func HasReferencedNotice() predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReferencedNoticeTable, ReferencedNoticeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferencedNoticeWith applies the HasEdge predicate on the "referenced_notice" edge with a given conditions (other predicates).
func HasReferencedNoticeWith(preds ...predicate.Conversation) predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := newReferencedNoticeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReferencedByConversations applies the HasEdge predicate on the "referenced_by_conversations" edge.
func HasReferencedByConversations() predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReferencedByConversationsTable, ReferencedByConversationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferencedByConversationsWith applies the HasEdge predicate on the "referenced_by_conversations" edge with a given conditions (other predicates).
func HasReferencedByConversationsWith(preds ...predicate.Conversation) predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := newReferencedByConversationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.ConversationMessage) predicate.Conversation {
	return predicate.Conversation(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Conversation) predicate.Conversation {
	return predicate.Conversation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Conversation) predicate.Conversation {
	return predicate.Conversation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Conversation) predicate.Conversation {
	return predicate.Conversation(sql.NotPredicates(p))
}
