// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ConversationUpdate is the builder for updating Conversation entities.
type ConversationUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationMutation
}

// Where appends a list predicates to the ConversationUpdate builder.
func (_u *ConversationUpdate) Where(ps ...predicate.Conversation) *ConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationUpdate) SetUpdatedAt(v time.Time) *ConversationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ConversationUpdate) SetUserID(v int64) *ConversationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableUserID(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *ConversationUpdate) SetSubject(v string) *ConversationUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableSubject(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationUpdate) SetStatus(v string) *ConversationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableStatus(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ConversationUpdate) SetKind(v string) *ConversationUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableKind(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ConversationUpdate) SetPriority(v string) *ConversationUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillablePriority(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ConversationUpdate) SetType(v string) *ConversationUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableType(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ConversationUpdate) SetSource(v string) *ConversationUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableSource(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ConversationUpdate) SetSourceID(v string) *ConversationUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableSourceID(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetReferencedNoticeID sets the "referenced_notice_id" field.
func (_u *ConversationUpdate) SetReferencedNoticeID(v int64) *ConversationUpdate {
	_u.mutation.SetReferencedNoticeID(v)
	return _u
}

// SetNillableReferencedNoticeID sets the "referenced_notice_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableReferencedNoticeID(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetReferencedNoticeID(*v)
	}
	return _u
}

// ClearReferencedNoticeID clears the value of the "referenced_notice_id" field.
func (_u *ConversationUpdate) ClearReferencedNoticeID() *ConversationUpdate {
	_u.mutation.ClearReferencedNoticeID()
	return _u
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (_u *ConversationUpdate) SetAssignedAdminID(v int64) *ConversationUpdate {
	_u.mutation.SetAssignedAdminID(v)
	return _u
}

// SetNillableAssignedAdminID sets the "assigned_admin_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableAssignedAdminID(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetAssignedAdminID(*v)
	}
	return _u
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (_u *ConversationUpdate) ClearAssignedAdminID() *ConversationUpdate {
	_u.mutation.ClearAssignedAdminID()
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *ConversationUpdate) SetLastMessageID(v int64) *ConversationUpdate {
	_u.mutation.ResetLastMessageID()
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastMessageID(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// AddLastMessageID adds value to the "last_message_id" field.
func (_u *ConversationUpdate) AddLastMessageID(v int64) *ConversationUpdate {
	_u.mutation.AddLastMessageID(v)
	return _u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (_u *ConversationUpdate) ClearLastMessageID() *ConversationUpdate {
	_u.mutation.ClearLastMessageID()
	return _u
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (_u *ConversationUpdate) SetLastMessageSenderType(v string) *ConversationUpdate {
	_u.mutation.SetLastMessageSenderType(v)
	return _u
}

// SetNillableLastMessageSenderType sets the "last_message_sender_type" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastMessageSenderType(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetLastMessageSenderType(*v)
	}
	return _u
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (_u *ConversationUpdate) SetLastMessageExcerpt(v string) *ConversationUpdate {
	_u.mutation.SetLastMessageExcerpt(v)
	return _u
}

// SetNillableLastMessageExcerpt sets the "last_message_excerpt" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastMessageExcerpt(v *string) *ConversationUpdate {
	if v != nil {
		_u.SetLastMessageExcerpt(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ConversationUpdate) SetLastMessageAt(v time.Time) *ConversationUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableLastMessageAt(v *time.Time) *ConversationUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (_u *ConversationUpdate) SetUserLastReadMessageID(v int64) *ConversationUpdate {
	_u.mutation.ResetUserLastReadMessageID()
	_u.mutation.SetUserLastReadMessageID(v)
	return _u
}

// SetNillableUserLastReadMessageID sets the "user_last_read_message_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableUserLastReadMessageID(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetUserLastReadMessageID(*v)
	}
	return _u
}

// AddUserLastReadMessageID adds value to the "user_last_read_message_id" field.
func (_u *ConversationUpdate) AddUserLastReadMessageID(v int64) *ConversationUpdate {
	_u.mutation.AddUserLastReadMessageID(v)
	return _u
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (_u *ConversationUpdate) ClearUserLastReadMessageID() *ConversationUpdate {
	_u.mutation.ClearUserLastReadMessageID()
	return _u
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (_u *ConversationUpdate) SetUserLastReadAt(v time.Time) *ConversationUpdate {
	_u.mutation.SetUserLastReadAt(v)
	return _u
}

// SetNillableUserLastReadAt sets the "user_last_read_at" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableUserLastReadAt(v *time.Time) *ConversationUpdate {
	if v != nil {
		_u.SetUserLastReadAt(*v)
	}
	return _u
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (_u *ConversationUpdate) ClearUserLastReadAt() *ConversationUpdate {
	_u.mutation.ClearUserLastReadAt()
	return _u
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (_u *ConversationUpdate) SetAdminLastReadMessageID(v int64) *ConversationUpdate {
	_u.mutation.ResetAdminLastReadMessageID()
	_u.mutation.SetAdminLastReadMessageID(v)
	return _u
}

// SetNillableAdminLastReadMessageID sets the "admin_last_read_message_id" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableAdminLastReadMessageID(v *int64) *ConversationUpdate {
	if v != nil {
		_u.SetAdminLastReadMessageID(*v)
	}
	return _u
}

// AddAdminLastReadMessageID adds value to the "admin_last_read_message_id" field.
func (_u *ConversationUpdate) AddAdminLastReadMessageID(v int64) *ConversationUpdate {
	_u.mutation.AddAdminLastReadMessageID(v)
	return _u
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (_u *ConversationUpdate) ClearAdminLastReadMessageID() *ConversationUpdate {
	_u.mutation.ClearAdminLastReadMessageID()
	return _u
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (_u *ConversationUpdate) SetAdminLastReadAt(v time.Time) *ConversationUpdate {
	_u.mutation.SetAdminLastReadAt(v)
	return _u
}

// SetNillableAdminLastReadAt sets the "admin_last_read_at" field if the given value is not nil.
func (_u *ConversationUpdate) SetNillableAdminLastReadAt(v *time.Time) *ConversationUpdate {
	if v != nil {
		_u.SetAdminLastReadAt(*v)
	}
	return _u
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (_u *ConversationUpdate) ClearAdminLastReadAt() *ConversationUpdate {
	_u.mutation.ClearAdminLastReadAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ConversationUpdate) SetUser(v *User) *ConversationUpdate {
	return _u.SetUserID(v.ID)
}

// SetAssignedAdmin sets the "assigned_admin" edge to the User entity.
func (_u *ConversationUpdate) SetAssignedAdmin(v *User) *ConversationUpdate {
	return _u.SetAssignedAdminID(v.ID)
}

// SetReferencedNotice sets the "referenced_notice" edge to the Conversation entity.
func (_u *ConversationUpdate) SetReferencedNotice(v *Conversation) *ConversationUpdate {
	return _u.SetReferencedNoticeID(v.ID)
}

// AddReferencedByConversationIDs adds the "referenced_by_conversations" edge to the Conversation entity by IDs.
func (_u *ConversationUpdate) AddReferencedByConversationIDs(ids ...int64) *ConversationUpdate {
	_u.mutation.AddReferencedByConversationIDs(ids...)
	return _u
}

// AddReferencedByConversations adds the "referenced_by_conversations" edges to the Conversation entity.
func (_u *ConversationUpdate) AddReferencedByConversations(v ...*Conversation) *ConversationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferencedByConversationIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the ConversationMessage entity by IDs.
func (_u *ConversationUpdate) AddMessageIDs(ids ...int64) *ConversationUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ConversationMessage entity.
func (_u *ConversationUpdate) AddMessages(v ...*ConversationMessage) *ConversationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_u *ConversationUpdate) Mutation() *ConversationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ConversationUpdate) ClearUser() *ConversationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAssignedAdmin clears the "assigned_admin" edge to the User entity.
func (_u *ConversationUpdate) ClearAssignedAdmin() *ConversationUpdate {
	_u.mutation.ClearAssignedAdmin()
	return _u
}

// ClearReferencedNotice clears the "referenced_notice" edge to the Conversation entity.
func (_u *ConversationUpdate) ClearReferencedNotice() *ConversationUpdate {
	_u.mutation.ClearReferencedNotice()
	return _u
}

// ClearReferencedByConversations clears all "referenced_by_conversations" edges to the Conversation entity.
func (_u *ConversationUpdate) ClearReferencedByConversations() *ConversationUpdate {
	_u.mutation.ClearReferencedByConversations()
	return _u
}

// RemoveReferencedByConversationIDs removes the "referenced_by_conversations" edge to Conversation entities by IDs.
func (_u *ConversationUpdate) RemoveReferencedByConversationIDs(ids ...int64) *ConversationUpdate {
	_u.mutation.RemoveReferencedByConversationIDs(ids...)
	return _u
}

// RemoveReferencedByConversations removes "referenced_by_conversations" edges to Conversation entities.
func (_u *ConversationUpdate) RemoveReferencedByConversations(v ...*Conversation) *ConversationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferencedByConversationIDs(ids...)
}

// ClearMessages clears all "messages" edges to the ConversationMessage entity.
func (_u *ConversationUpdate) ClearMessages() *ConversationUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ConversationMessage entities by IDs.
func (_u *ConversationUpdate) RemoveMessageIDs(ids ...int64) *ConversationUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ConversationMessage entities.
func (_u *ConversationUpdate) RemoveMessages(v ...*ConversationMessage) *ConversationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationUpdate) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := conversation.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Conversation.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := conversation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Conversation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := conversation.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Conversation.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := conversation.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Conversation.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := conversation.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Conversation.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := conversation.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Conversation.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := conversation.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "Conversation.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessageSenderType(); ok {
		if err := conversation.LastMessageSenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "last_message_sender_type", err: fmt.Errorf(`ent: validator failed for field "Conversation.last_message_sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessageExcerpt(); ok {
		if err := conversation.LastMessageExcerptValidator(v); err != nil {
			return &ValidationError{Name: "last_message_excerpt", err: fmt.Errorf(`ent: validator failed for field "Conversation.last_message_excerpt": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Conversation.user"`)
	}
	return nil
}

func (_u *ConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(conversation.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(conversation.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(conversation.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(conversation.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(conversation.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(conversation.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageID(); ok {
		_spec.SetField(conversation.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastMessageID(); ok {
		_spec.AddField(conversation.FieldLastMessageID, field.TypeInt64, value)
	}
	if _u.mutation.LastMessageIDCleared() {
		_spec.ClearField(conversation.FieldLastMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastMessageSenderType(); ok {
		_spec.SetField(conversation.FieldLastMessageSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageExcerpt(); ok {
		_spec.SetField(conversation.FieldLastMessageExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(conversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserLastReadMessageID(); ok {
		_spec.SetField(conversation.FieldUserLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserLastReadMessageID(); ok {
		_spec.AddField(conversation.FieldUserLastReadMessageID, field.TypeInt64, value)
	}
	if _u.mutation.UserLastReadMessageIDCleared() {
		_spec.ClearField(conversation.FieldUserLastReadMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserLastReadAt(); ok {
		_spec.SetField(conversation.FieldUserLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.UserLastReadAtCleared() {
		_spec.ClearField(conversation.FieldUserLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AdminLastReadMessageID(); ok {
		_spec.SetField(conversation.FieldAdminLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminLastReadMessageID(); ok {
		_spec.AddField(conversation.FieldAdminLastReadMessageID, field.TypeInt64, value)
	}
	if _u.mutation.AdminLastReadMessageIDCleared() {
		_spec.ClearField(conversation.FieldAdminLastReadMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminLastReadAt(); ok {
		_spec.SetField(conversation.FieldAdminLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.AdminLastReadAtCleared() {
		_spec.ClearField(conversation.FieldAdminLastReadAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.UserTable,
			Columns: []string{conversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.UserTable,
			Columns: []string{conversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedAdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.AssignedAdminTable,
			Columns: []string{conversation.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.AssignedAdminTable,
			Columns: []string{conversation.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferencedNoticeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.ReferencedNoticeTable,
			Columns: []string{conversation.ReferencedNoticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencedNoticeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.ReferencedNoticeTable,
			Columns: []string{conversation.ReferencedNoticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferencedByConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ReferencedByConversationsTable,
			Columns: []string{conversation.ReferencedByConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferencedByConversationsIDs(); len(nodes) > 0 && !_u.mutation.ReferencedByConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ReferencedByConversationsTable,
			Columns: []string{conversation.ReferencedByConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencedByConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ReferencedByConversationsTable,
			Columns: []string{conversation.ReferencedByConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationUpdateOne is the builder for updating a single Conversation entity.
type ConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConversationUpdateOne) SetUpdatedAt(v time.Time) *ConversationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ConversationUpdateOne) SetUserID(v int64) *ConversationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableUserID(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *ConversationUpdateOne) SetSubject(v string) *ConversationUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableSubject(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ConversationUpdateOne) SetStatus(v string) *ConversationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableStatus(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ConversationUpdateOne) SetKind(v string) *ConversationUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableKind(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ConversationUpdateOne) SetPriority(v string) *ConversationUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillablePriority(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ConversationUpdateOne) SetType(v string) *ConversationUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableType(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ConversationUpdateOne) SetSource(v string) *ConversationUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableSource(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *ConversationUpdateOne) SetSourceID(v string) *ConversationUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableSourceID(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// SetReferencedNoticeID sets the "referenced_notice_id" field.
func (_u *ConversationUpdateOne) SetReferencedNoticeID(v int64) *ConversationUpdateOne {
	_u.mutation.SetReferencedNoticeID(v)
	return _u
}

// SetNillableReferencedNoticeID sets the "referenced_notice_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableReferencedNoticeID(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetReferencedNoticeID(*v)
	}
	return _u
}

// ClearReferencedNoticeID clears the value of the "referenced_notice_id" field.
func (_u *ConversationUpdateOne) ClearReferencedNoticeID() *ConversationUpdateOne {
	_u.mutation.ClearReferencedNoticeID()
	return _u
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (_u *ConversationUpdateOne) SetAssignedAdminID(v int64) *ConversationUpdateOne {
	_u.mutation.SetAssignedAdminID(v)
	return _u
}

// SetNillableAssignedAdminID sets the "assigned_admin_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableAssignedAdminID(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetAssignedAdminID(*v)
	}
	return _u
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (_u *ConversationUpdateOne) ClearAssignedAdminID() *ConversationUpdateOne {
	_u.mutation.ClearAssignedAdminID()
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *ConversationUpdateOne) SetLastMessageID(v int64) *ConversationUpdateOne {
	_u.mutation.ResetLastMessageID()
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastMessageID(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// AddLastMessageID adds value to the "last_message_id" field.
func (_u *ConversationUpdateOne) AddLastMessageID(v int64) *ConversationUpdateOne {
	_u.mutation.AddLastMessageID(v)
	return _u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (_u *ConversationUpdateOne) ClearLastMessageID() *ConversationUpdateOne {
	_u.mutation.ClearLastMessageID()
	return _u
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (_u *ConversationUpdateOne) SetLastMessageSenderType(v string) *ConversationUpdateOne {
	_u.mutation.SetLastMessageSenderType(v)
	return _u
}

// SetNillableLastMessageSenderType sets the "last_message_sender_type" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastMessageSenderType(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastMessageSenderType(*v)
	}
	return _u
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (_u *ConversationUpdateOne) SetLastMessageExcerpt(v string) *ConversationUpdateOne {
	_u.mutation.SetLastMessageExcerpt(v)
	return _u
}

// SetNillableLastMessageExcerpt sets the "last_message_excerpt" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastMessageExcerpt(v *string) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastMessageExcerpt(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *ConversationUpdateOne) SetLastMessageAt(v time.Time) *ConversationUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableLastMessageAt(v *time.Time) *ConversationUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (_u *ConversationUpdateOne) SetUserLastReadMessageID(v int64) *ConversationUpdateOne {
	_u.mutation.ResetUserLastReadMessageID()
	_u.mutation.SetUserLastReadMessageID(v)
	return _u
}

// SetNillableUserLastReadMessageID sets the "user_last_read_message_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableUserLastReadMessageID(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetUserLastReadMessageID(*v)
	}
	return _u
}

// AddUserLastReadMessageID adds value to the "user_last_read_message_id" field.
func (_u *ConversationUpdateOne) AddUserLastReadMessageID(v int64) *ConversationUpdateOne {
	_u.mutation.AddUserLastReadMessageID(v)
	return _u
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (_u *ConversationUpdateOne) ClearUserLastReadMessageID() *ConversationUpdateOne {
	_u.mutation.ClearUserLastReadMessageID()
	return _u
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (_u *ConversationUpdateOne) SetUserLastReadAt(v time.Time) *ConversationUpdateOne {
	_u.mutation.SetUserLastReadAt(v)
	return _u
}

// SetNillableUserLastReadAt sets the "user_last_read_at" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableUserLastReadAt(v *time.Time) *ConversationUpdateOne {
	if v != nil {
		_u.SetUserLastReadAt(*v)
	}
	return _u
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (_u *ConversationUpdateOne) ClearUserLastReadAt() *ConversationUpdateOne {
	_u.mutation.ClearUserLastReadAt()
	return _u
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (_u *ConversationUpdateOne) SetAdminLastReadMessageID(v int64) *ConversationUpdateOne {
	_u.mutation.ResetAdminLastReadMessageID()
	_u.mutation.SetAdminLastReadMessageID(v)
	return _u
}

// SetNillableAdminLastReadMessageID sets the "admin_last_read_message_id" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableAdminLastReadMessageID(v *int64) *ConversationUpdateOne {
	if v != nil {
		_u.SetAdminLastReadMessageID(*v)
	}
	return _u
}

// AddAdminLastReadMessageID adds value to the "admin_last_read_message_id" field.
func (_u *ConversationUpdateOne) AddAdminLastReadMessageID(v int64) *ConversationUpdateOne {
	_u.mutation.AddAdminLastReadMessageID(v)
	return _u
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (_u *ConversationUpdateOne) ClearAdminLastReadMessageID() *ConversationUpdateOne {
	_u.mutation.ClearAdminLastReadMessageID()
	return _u
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (_u *ConversationUpdateOne) SetAdminLastReadAt(v time.Time) *ConversationUpdateOne {
	_u.mutation.SetAdminLastReadAt(v)
	return _u
}

// SetNillableAdminLastReadAt sets the "admin_last_read_at" field if the given value is not nil.
func (_u *ConversationUpdateOne) SetNillableAdminLastReadAt(v *time.Time) *ConversationUpdateOne {
	if v != nil {
		_u.SetAdminLastReadAt(*v)
	}
	return _u
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (_u *ConversationUpdateOne) ClearAdminLastReadAt() *ConversationUpdateOne {
	_u.mutation.ClearAdminLastReadAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ConversationUpdateOne) SetUser(v *User) *ConversationUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAssignedAdmin sets the "assigned_admin" edge to the User entity.
func (_u *ConversationUpdateOne) SetAssignedAdmin(v *User) *ConversationUpdateOne {
	return _u.SetAssignedAdminID(v.ID)
}

// SetReferencedNotice sets the "referenced_notice" edge to the Conversation entity.
func (_u *ConversationUpdateOne) SetReferencedNotice(v *Conversation) *ConversationUpdateOne {
	return _u.SetReferencedNoticeID(v.ID)
}

// AddReferencedByConversationIDs adds the "referenced_by_conversations" edge to the Conversation entity by IDs.
func (_u *ConversationUpdateOne) AddReferencedByConversationIDs(ids ...int64) *ConversationUpdateOne {
	_u.mutation.AddReferencedByConversationIDs(ids...)
	return _u
}

// AddReferencedByConversations adds the "referenced_by_conversations" edges to the Conversation entity.
func (_u *ConversationUpdateOne) AddReferencedByConversations(v ...*Conversation) *ConversationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReferencedByConversationIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the ConversationMessage entity by IDs.
func (_u *ConversationUpdateOne) AddMessageIDs(ids ...int64) *ConversationUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ConversationMessage entity.
func (_u *ConversationUpdateOne) AddMessages(v ...*ConversationMessage) *ConversationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_u *ConversationUpdateOne) Mutation() *ConversationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ConversationUpdateOne) ClearUser() *ConversationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAssignedAdmin clears the "assigned_admin" edge to the User entity.
func (_u *ConversationUpdateOne) ClearAssignedAdmin() *ConversationUpdateOne {
	_u.mutation.ClearAssignedAdmin()
	return _u
}

// ClearReferencedNotice clears the "referenced_notice" edge to the Conversation entity.
func (_u *ConversationUpdateOne) ClearReferencedNotice() *ConversationUpdateOne {
	_u.mutation.ClearReferencedNotice()
	return _u
}

// ClearReferencedByConversations clears all "referenced_by_conversations" edges to the Conversation entity.
func (_u *ConversationUpdateOne) ClearReferencedByConversations() *ConversationUpdateOne {
	_u.mutation.ClearReferencedByConversations()
	return _u
}

// RemoveReferencedByConversationIDs removes the "referenced_by_conversations" edge to Conversation entities by IDs.
func (_u *ConversationUpdateOne) RemoveReferencedByConversationIDs(ids ...int64) *ConversationUpdateOne {
	_u.mutation.RemoveReferencedByConversationIDs(ids...)
	return _u
}

// RemoveReferencedByConversations removes "referenced_by_conversations" edges to Conversation entities.
func (_u *ConversationUpdateOne) RemoveReferencedByConversations(v ...*Conversation) *ConversationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReferencedByConversationIDs(ids...)
}

// ClearMessages clears all "messages" edges to the ConversationMessage entity.
func (_u *ConversationUpdateOne) ClearMessages() *ConversationUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ConversationMessage entities by IDs.
func (_u *ConversationUpdateOne) RemoveMessageIDs(ids ...int64) *ConversationUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ConversationMessage entities.
func (_u *ConversationUpdateOne) RemoveMessages(v ...*ConversationMessage) *ConversationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ConversationUpdate builder.
func (_u *ConversationUpdateOne) Where(ps ...predicate.Conversation) *ConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationUpdateOne) Select(field string, fields ...string) *ConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Conversation entity.
func (_u *ConversationUpdateOne) Save(ctx context.Context) (*Conversation, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationUpdateOne) SaveX(ctx context.Context) *Conversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConversationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := conversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationUpdateOne) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := conversation.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Conversation.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := conversation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Conversation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := conversation.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Conversation.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := conversation.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Conversation.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := conversation.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Conversation.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := conversation.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Conversation.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := conversation.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "Conversation.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessageSenderType(); ok {
		if err := conversation.LastMessageSenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "last_message_sender_type", err: fmt.Errorf(`ent: validator failed for field "Conversation.last_message_sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastMessageExcerpt(); ok {
		if err := conversation.LastMessageExcerptValidator(v); err != nil {
			return &ValidationError{Name: "last_message_excerpt", err: fmt.Errorf(`ent: validator failed for field "Conversation.last_message_excerpt": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Conversation.user"`)
	}
	return nil
}

func (_u *ConversationUpdateOne) sqlSave(ctx context.Context) (_node *Conversation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversation.Table, conversation.Columns, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Conversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversation.FieldID)
		for _, f := range fields {
			if !conversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(conversation.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(conversation.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(conversation.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(conversation.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(conversation.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(conversation.FieldSourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageID(); ok {
		_spec.SetField(conversation.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastMessageID(); ok {
		_spec.AddField(conversation.FieldLastMessageID, field.TypeInt64, value)
	}
	if _u.mutation.LastMessageIDCleared() {
		_spec.ClearField(conversation.FieldLastMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastMessageSenderType(); ok {
		_spec.SetField(conversation.FieldLastMessageSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageExcerpt(); ok {
		_spec.SetField(conversation.FieldLastMessageExcerpt, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(conversation.FieldLastMessageAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserLastReadMessageID(); ok {
		_spec.SetField(conversation.FieldUserLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserLastReadMessageID(); ok {
		_spec.AddField(conversation.FieldUserLastReadMessageID, field.TypeInt64, value)
	}
	if _u.mutation.UserLastReadMessageIDCleared() {
		_spec.ClearField(conversation.FieldUserLastReadMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserLastReadAt(); ok {
		_spec.SetField(conversation.FieldUserLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.UserLastReadAtCleared() {
		_spec.ClearField(conversation.FieldUserLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AdminLastReadMessageID(); ok {
		_spec.SetField(conversation.FieldAdminLastReadMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminLastReadMessageID(); ok {
		_spec.AddField(conversation.FieldAdminLastReadMessageID, field.TypeInt64, value)
	}
	if _u.mutation.AdminLastReadMessageIDCleared() {
		_spec.ClearField(conversation.FieldAdminLastReadMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminLastReadAt(); ok {
		_spec.SetField(conversation.FieldAdminLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.AdminLastReadAtCleared() {
		_spec.ClearField(conversation.FieldAdminLastReadAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.UserTable,
			Columns: []string{conversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.UserTable,
			Columns: []string{conversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedAdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.AssignedAdminTable,
			Columns: []string{conversation.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.AssignedAdminTable,
			Columns: []string{conversation.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferencedNoticeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.ReferencedNoticeTable,
			Columns: []string{conversation.ReferencedNoticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencedNoticeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.ReferencedNoticeTable,
			Columns: []string{conversation.ReferencedNoticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReferencedByConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ReferencedByConversationsTable,
			Columns: []string{conversation.ReferencedByConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReferencedByConversationsIDs(); len(nodes) > 0 && !_u.mutation.ReferencedByConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ReferencedByConversationsTable,
			Columns: []string{conversation.ReferencedByConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferencedByConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ReferencedByConversationsTable,
			Columns: []string{conversation.ReferencedByConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Conversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
