// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ConversationMessageCreate is the builder for creating a ConversationMessage entity.
type ConversationMessageCreate struct {
	config
	mutation *ConversationMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConversationID sets the "conversation_id" field.
func (_c *ConversationMessageCreate) SetConversationID(v int64) *ConversationMessageCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetSenderType sets the "sender_type" field.
func (_c *ConversationMessageCreate) SetSenderType(v string) *ConversationMessageCreate {
	_c.mutation.SetSenderType(v)
	return _c
}

// SetSenderID sets the "sender_id" field.
func (_c *ConversationMessageCreate) SetSenderID(v int64) *ConversationMessageCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableSenderID(v *int64) *ConversationMessageCreate {
	if v != nil {
		_c.SetSenderID(*v)
	}
	return _c
}

// SetMessageType sets the "message_type" field.
func (_c *ConversationMessageCreate) SetMessageType(v string) *ConversationMessageCreate {
	_c.mutation.SetMessageType(v)
	return _c
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableMessageType(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetMessageType(*v)
	}
	return _c
}

// SetContentFormat sets the "content_format" field.
func (_c *ConversationMessageCreate) SetContentFormat(v string) *ConversationMessageCreate {
	_c.mutation.SetContentFormat(v)
	return _c
}

// SetNillableContentFormat sets the "content_format" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableContentFormat(v *string) *ConversationMessageCreate {
	if v != nil {
		_c.SetContentFormat(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *ConversationMessageCreate) SetContent(v string) *ConversationMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ConversationMessageCreate) SetMetadata(v map[string]interface{}) *ConversationMessageCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationMessageCreate) SetCreatedAt(v time.Time) *ConversationMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationMessageCreate) SetNillableCreatedAt(v *time.Time) *ConversationMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_c *ConversationMessageCreate) SetConversation(v *Conversation) *ConversationMessageCreate {
	return _c.SetConversationID(v.ID)
}

// SetSender sets the "sender" edge to the User entity.
func (_c *ConversationMessageCreate) SetSender(v *User) *ConversationMessageCreate {
	return _c.SetSenderID(v.ID)
}

// Mutation returns the ConversationMessageMutation object of the builder.
func (_c *ConversationMessageCreate) Mutation() *ConversationMessageMutation {
	return _c.mutation
}

// Save creates the ConversationMessage in the database.
func (_c *ConversationMessageCreate) Save(ctx context.Context) (*ConversationMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationMessageCreate) SaveX(ctx context.Context) *ConversationMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationMessageCreate) defaults() {
	if _, ok := _c.mutation.MessageType(); !ok {
		v := conversationmessage.DefaultMessageType
		_c.mutation.SetMessageType(v)
	}
	if _, ok := _c.mutation.ContentFormat(); !ok {
		v := conversationmessage.DefaultContentFormat
		_c.mutation.SetContentFormat(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversationmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationMessageCreate) check() error {
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "ConversationMessage.conversation_id"`)}
	}
	if _, ok := _c.mutation.SenderType(); !ok {
		return &ValidationError{Name: "sender_type", err: errors.New(`ent: missing required field "ConversationMessage.sender_type"`)}
	}
	if v, ok := _c.mutation.SenderType(); ok {
		if err := conversationmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.sender_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MessageType(); !ok {
		return &ValidationError{Name: "message_type", err: errors.New(`ent: missing required field "ConversationMessage.message_type"`)}
	}
	if v, ok := _c.mutation.MessageType(); ok {
		if err := conversationmessage.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.message_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentFormat(); !ok {
		return &ValidationError{Name: "content_format", err: errors.New(`ent: missing required field "ConversationMessage.content_format"`)}
	}
	if v, ok := _c.mutation.ContentFormat(); ok {
		if err := conversationmessage.ContentFormatValidator(v); err != nil {
			return &ValidationError{Name: "content_format", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.content_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ConversationMessage.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := conversationmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ConversationMessage.created_at"`)}
	}
	if len(_c.mutation.ConversationIDs()) == 0 {
		return &ValidationError{Name: "conversation", err: errors.New(`ent: missing required edge "ConversationMessage.conversation"`)}
	}
	return nil
}

func (_c *ConversationMessageCreate) sqlSave(ctx context.Context) (*ConversationMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationMessageCreate) createSpec() (*ConversationMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ConversationMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversationmessage.Table, sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SenderType(); ok {
		_spec.SetField(conversationmessage.FieldSenderType, field.TypeString, value)
		_node.SenderType = value
	}
	if value, ok := _c.mutation.MessageType(); ok {
		_spec.SetField(conversationmessage.FieldMessageType, field.TypeString, value)
		_node.MessageType = value
	}
	if value, ok := _c.mutation.ContentFormat(); ok {
		_spec.SetField(conversationmessage.FieldContentFormat, field.TypeString, value)
		_node.ContentFormat = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(conversationmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(conversationmessage.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversationmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConversationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.SenderTable,
			Columns: []string{conversationmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SenderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConversationMessage.Create().
//		SetConversationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationMessageUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationMessageCreate) OnConflict(opts ...sql.ConflictOption) *ConversationMessageUpsertOne {
	_c.conflict = opts
	return &ConversationMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationMessageCreate) OnConflictColumns(columns ...string) *ConversationMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationMessageUpsertOne{
		create: _c,
	}
}

type (
	// ConversationMessageUpsertOne is the builder for "upsert"-ing
	//  one ConversationMessage node.
	ConversationMessageUpsertOne struct {
		create *ConversationMessageCreate
	}

	// ConversationMessageUpsert is the "OnConflict" setter.
	ConversationMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetConversationID sets the "conversation_id" field.
func (u *ConversationMessageUpsert) SetConversationID(v int64) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateConversationID() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldConversationID)
	return u
}

// SetSenderType sets the "sender_type" field.
func (u *ConversationMessageUpsert) SetSenderType(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldSenderType, v)
	return u
}

// UpdateSenderType sets the "sender_type" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateSenderType() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldSenderType)
	return u
}

// SetSenderID sets the "sender_id" field.
func (u *ConversationMessageUpsert) SetSenderID(v int64) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldSenderID, v)
	return u
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateSenderID() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldSenderID)
	return u
}

// ClearSenderID clears the value of the "sender_id" field.
func (u *ConversationMessageUpsert) ClearSenderID() *ConversationMessageUpsert {
	u.SetNull(conversationmessage.FieldSenderID)
	return u
}

// SetMessageType sets the "message_type" field.
func (u *ConversationMessageUpsert) SetMessageType(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldMessageType, v)
	return u
}

// UpdateMessageType sets the "message_type" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateMessageType() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldMessageType)
	return u
}

// SetContentFormat sets the "content_format" field.
func (u *ConversationMessageUpsert) SetContentFormat(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldContentFormat, v)
	return u
}

// UpdateContentFormat sets the "content_format" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateContentFormat() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldContentFormat)
	return u
}

// SetContent sets the "content" field.
func (u *ConversationMessageUpsert) SetContent(v string) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateContent() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldContent)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ConversationMessageUpsert) SetMetadata(v map[string]interface{}) *ConversationMessageUpsert {
	u.Set(conversationmessage.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ConversationMessageUpsert) UpdateMetadata() *ConversationMessageUpsert {
	u.SetExcluded(conversationmessage.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ConversationMessageUpsert) ClearMetadata() *ConversationMessageUpsert {
	u.SetNull(conversationmessage.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationMessageUpsertOne) UpdateNewValues() *ConversationMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(conversationmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConversationMessageUpsertOne) Ignore() *ConversationMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationMessageUpsertOne) DoNothing() *ConversationMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationMessageCreate.OnConflict
// documentation for more info.
func (u *ConversationMessageUpsertOne) Update(set func(*ConversationMessageUpsert)) *ConversationMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ConversationMessageUpsertOne) SetConversationID(v int64) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateConversationID() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetSenderType sets the "sender_type" field.
func (u *ConversationMessageUpsertOne) SetSenderType(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetSenderType(v)
	})
}

// UpdateSenderType sets the "sender_type" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateSenderType() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateSenderType()
	})
}

// SetSenderID sets the "sender_id" field.
func (u *ConversationMessageUpsertOne) SetSenderID(v int64) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateSenderID() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateSenderID()
	})
}

// ClearSenderID clears the value of the "sender_id" field.
func (u *ConversationMessageUpsertOne) ClearSenderID() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearSenderID()
	})
}

// SetMessageType sets the "message_type" field.
func (u *ConversationMessageUpsertOne) SetMessageType(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetMessageType(v)
	})
}

// UpdateMessageType sets the "message_type" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateMessageType() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateMessageType()
	})
}

// SetContentFormat sets the "content_format" field.
func (u *ConversationMessageUpsertOne) SetContentFormat(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetContentFormat(v)
	})
}

// UpdateContentFormat sets the "content_format" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateContentFormat() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateContentFormat()
	})
}

// SetContent sets the "content" field.
func (u *ConversationMessageUpsertOne) SetContent(v string) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateContent() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateContent()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ConversationMessageUpsertOne) SetMetadata(v map[string]interface{}) *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ConversationMessageUpsertOne) UpdateMetadata() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ConversationMessageUpsertOne) ClearMetadata() *ConversationMessageUpsertOne {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *ConversationMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConversationMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConversationMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConversationMessageCreateBulk is the builder for creating many ConversationMessage entities in bulk.
type ConversationMessageCreateBulk struct {
	config
	err      error
	builders []*ConversationMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the ConversationMessage entities in the database.
func (_c *ConversationMessageCreateBulk) Save(ctx context.Context) ([]*ConversationMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ConversationMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationMessageCreateBulk) SaveX(ctx context.Context) []*ConversationMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ConversationMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationMessageUpsert) {
//			SetConversationID(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConversationMessageUpsertBulk {
	_c.conflict = opts
	return &ConversationMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationMessageCreateBulk) OnConflictColumns(columns ...string) *ConversationMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationMessageUpsertBulk{
		create: _c,
	}
}

// ConversationMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of ConversationMessage nodes.
type ConversationMessageUpsertBulk struct {
	create *ConversationMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationMessageUpsertBulk) UpdateNewValues() *ConversationMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(conversationmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ConversationMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConversationMessageUpsertBulk) Ignore() *ConversationMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationMessageUpsertBulk) DoNothing() *ConversationMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationMessageCreateBulk.OnConflict
// documentation for more info.
func (u *ConversationMessageUpsertBulk) Update(set func(*ConversationMessageUpsert)) *ConversationMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ConversationMessageUpsertBulk) SetConversationID(v int64) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateConversationID() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetSenderType sets the "sender_type" field.
func (u *ConversationMessageUpsertBulk) SetSenderType(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetSenderType(v)
	})
}

// UpdateSenderType sets the "sender_type" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateSenderType() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateSenderType()
	})
}

// SetSenderID sets the "sender_id" field.
func (u *ConversationMessageUpsertBulk) SetSenderID(v int64) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateSenderID() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateSenderID()
	})
}

// ClearSenderID clears the value of the "sender_id" field.
func (u *ConversationMessageUpsertBulk) ClearSenderID() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearSenderID()
	})
}

// SetMessageType sets the "message_type" field.
func (u *ConversationMessageUpsertBulk) SetMessageType(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetMessageType(v)
	})
}

// UpdateMessageType sets the "message_type" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateMessageType() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateMessageType()
	})
}

// SetContentFormat sets the "content_format" field.
func (u *ConversationMessageUpsertBulk) SetContentFormat(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetContentFormat(v)
	})
}

// UpdateContentFormat sets the "content_format" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateContentFormat() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateContentFormat()
	})
}

// SetContent sets the "content" field.
func (u *ConversationMessageUpsertBulk) SetContent(v string) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateContent() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateContent()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ConversationMessageUpsertBulk) SetMetadata(v map[string]interface{}) *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ConversationMessageUpsertBulk) UpdateMetadata() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ConversationMessageUpsertBulk) ClearMetadata() *ConversationMessageUpsertBulk {
	return u.Update(func(s *ConversationMessageUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *ConversationMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConversationMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
