// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ConversationCreate is the builder for creating a Conversation entity.
type ConversationCreate struct {
	config
	mutation *ConversationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationCreate) SetCreatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableCreatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConversationCreate) SetUpdatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableUpdatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ConversationCreate) SetUserID(v int64) *ConversationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *ConversationCreate) SetSubject(v string) *ConversationCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ConversationCreate) SetStatus(v string) *ConversationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableStatus(v *string) *ConversationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *ConversationCreate) SetKind(v string) *ConversationCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableKind(v *string) *ConversationCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *ConversationCreate) SetPriority(v string) *ConversationCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *ConversationCreate) SetNillablePriority(v *string) *ConversationCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ConversationCreate) SetType(v string) *ConversationCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableType(v *string) *ConversationCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *ConversationCreate) SetSource(v string) *ConversationCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableSource(v *string) *ConversationCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *ConversationCreate) SetSourceID(v string) *ConversationCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableSourceID(v *string) *ConversationCreate {
	if v != nil {
		_c.SetSourceID(*v)
	}
	return _c
}

// SetReferencedNoticeID sets the "referenced_notice_id" field.
func (_c *ConversationCreate) SetReferencedNoticeID(v int64) *ConversationCreate {
	_c.mutation.SetReferencedNoticeID(v)
	return _c
}

// SetNillableReferencedNoticeID sets the "referenced_notice_id" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableReferencedNoticeID(v *int64) *ConversationCreate {
	if v != nil {
		_c.SetReferencedNoticeID(*v)
	}
	return _c
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (_c *ConversationCreate) SetAssignedAdminID(v int64) *ConversationCreate {
	_c.mutation.SetAssignedAdminID(v)
	return _c
}

// SetNillableAssignedAdminID sets the "assigned_admin_id" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableAssignedAdminID(v *int64) *ConversationCreate {
	if v != nil {
		_c.SetAssignedAdminID(*v)
	}
	return _c
}

// SetLastMessageID sets the "last_message_id" field.
func (_c *ConversationCreate) SetLastMessageID(v int64) *ConversationCreate {
	_c.mutation.SetLastMessageID(v)
	return _c
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableLastMessageID(v *int64) *ConversationCreate {
	if v != nil {
		_c.SetLastMessageID(*v)
	}
	return _c
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (_c *ConversationCreate) SetLastMessageSenderType(v string) *ConversationCreate {
	_c.mutation.SetLastMessageSenderType(v)
	return _c
}

// SetNillableLastMessageSenderType sets the "last_message_sender_type" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableLastMessageSenderType(v *string) *ConversationCreate {
	if v != nil {
		_c.SetLastMessageSenderType(*v)
	}
	return _c
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (_c *ConversationCreate) SetLastMessageExcerpt(v string) *ConversationCreate {
	_c.mutation.SetLastMessageExcerpt(v)
	return _c
}

// SetNillableLastMessageExcerpt sets the "last_message_excerpt" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableLastMessageExcerpt(v *string) *ConversationCreate {
	if v != nil {
		_c.SetLastMessageExcerpt(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *ConversationCreate) SetLastMessageAt(v time.Time) *ConversationCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableLastMessageAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (_c *ConversationCreate) SetUserLastReadMessageID(v int64) *ConversationCreate {
	_c.mutation.SetUserLastReadMessageID(v)
	return _c
}

// SetNillableUserLastReadMessageID sets the "user_last_read_message_id" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableUserLastReadMessageID(v *int64) *ConversationCreate {
	if v != nil {
		_c.SetUserLastReadMessageID(*v)
	}
	return _c
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (_c *ConversationCreate) SetUserLastReadAt(v time.Time) *ConversationCreate {
	_c.mutation.SetUserLastReadAt(v)
	return _c
}

// SetNillableUserLastReadAt sets the "user_last_read_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableUserLastReadAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetUserLastReadAt(*v)
	}
	return _c
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (_c *ConversationCreate) SetAdminLastReadMessageID(v int64) *ConversationCreate {
	_c.mutation.SetAdminLastReadMessageID(v)
	return _c
}

// SetNillableAdminLastReadMessageID sets the "admin_last_read_message_id" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableAdminLastReadMessageID(v *int64) *ConversationCreate {
	if v != nil {
		_c.SetAdminLastReadMessageID(*v)
	}
	return _c
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (_c *ConversationCreate) SetAdminLastReadAt(v time.Time) *ConversationCreate {
	_c.mutation.SetAdminLastReadAt(v)
	return _c
}

// SetNillableAdminLastReadAt sets the "admin_last_read_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableAdminLastReadAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetAdminLastReadAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ConversationCreate) SetUser(v *User) *ConversationCreate {
	return _c.SetUserID(v.ID)
}

// SetAssignedAdmin sets the "assigned_admin" edge to the User entity.
func (_c *ConversationCreate) SetAssignedAdmin(v *User) *ConversationCreate {
	return _c.SetAssignedAdminID(v.ID)
}

// SetReferencedNotice sets the "referenced_notice" edge to the Conversation entity.
func (_c *ConversationCreate) SetReferencedNotice(v *Conversation) *ConversationCreate {
	return _c.SetReferencedNoticeID(v.ID)
}

// AddReferencedByConversationIDs adds the "referenced_by_conversations" edge to the Conversation entity by IDs.
func (_c *ConversationCreate) AddReferencedByConversationIDs(ids ...int64) *ConversationCreate {
	_c.mutation.AddReferencedByConversationIDs(ids...)
	return _c
}

// AddReferencedByConversations adds the "referenced_by_conversations" edges to the Conversation entity.
func (_c *ConversationCreate) AddReferencedByConversations(v ...*Conversation) *ConversationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReferencedByConversationIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the ConversationMessage entity by IDs.
func (_c *ConversationCreate) AddMessageIDs(ids ...int64) *ConversationCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the ConversationMessage entity.
func (_c *ConversationCreate) AddMessages(v ...*ConversationMessage) *ConversationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_c *ConversationCreate) Mutation() *ConversationMutation {
	return _c.mutation
}

// Save creates the Conversation in the database.
func (_c *ConversationCreate) Save(ctx context.Context) (*Conversation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationCreate) SaveX(ctx context.Context) *Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := conversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := conversation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Kind(); !ok {
		v := conversation.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := conversation.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := conversation.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := conversation.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		v := conversation.DefaultSourceID
		_c.mutation.SetSourceID(v)
	}
	if _, ok := _c.mutation.LastMessageSenderType(); !ok {
		v := conversation.DefaultLastMessageSenderType
		_c.mutation.SetLastMessageSenderType(v)
	}
	if _, ok := _c.mutation.LastMessageExcerpt(); !ok {
		v := conversation.DefaultLastMessageExcerpt
		_c.mutation.SetLastMessageExcerpt(v)
	}
	if _, ok := _c.mutation.LastMessageAt(); !ok {
		v := conversation.DefaultLastMessageAt()
		_c.mutation.SetLastMessageAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Conversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Conversation.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Conversation.user_id"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "Conversation.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := conversation.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Conversation.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Conversation.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := conversation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Conversation.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Conversation.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := conversation.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Conversation.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Conversation.priority"`)}
	}
	if v, ok := _c.mutation.Priority(); ok {
		if err := conversation.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Conversation.priority": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Conversation.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := conversation.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Conversation.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "Conversation.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := conversation.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "Conversation.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "Conversation.source_id"`)}
	}
	if v, ok := _c.mutation.SourceID(); ok {
		if err := conversation.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "Conversation.source_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastMessageSenderType(); !ok {
		return &ValidationError{Name: "last_message_sender_type", err: errors.New(`ent: missing required field "Conversation.last_message_sender_type"`)}
	}
	if v, ok := _c.mutation.LastMessageSenderType(); ok {
		if err := conversation.LastMessageSenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "last_message_sender_type", err: fmt.Errorf(`ent: validator failed for field "Conversation.last_message_sender_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastMessageExcerpt(); !ok {
		return &ValidationError{Name: "last_message_excerpt", err: errors.New(`ent: missing required field "Conversation.last_message_excerpt"`)}
	}
	if v, ok := _c.mutation.LastMessageExcerpt(); ok {
		if err := conversation.LastMessageExcerptValidator(v); err != nil {
			return &ValidationError{Name: "last_message_excerpt", err: fmt.Errorf(`ent: validator failed for field "Conversation.last_message_excerpt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastMessageAt(); !ok {
		return &ValidationError{Name: "last_message_at", err: errors.New(`ent: missing required field "Conversation.last_message_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Conversation.user"`)}
	}
	return nil
}

func (_c *ConversationCreate) sqlSave(ctx context.Context) (*Conversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationCreate) createSpec() (*Conversation, *sqlgraph.CreateSpec) {
	var (
		_node = &Conversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversation.Table, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(conversation.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(conversation.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(conversation.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(conversation.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(conversation.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(conversation.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.LastMessageID(); ok {
		_spec.SetField(conversation.FieldLastMessageID, field.TypeInt64, value)
		_node.LastMessageID = &value
	}
	if value, ok := _c.mutation.LastMessageSenderType(); ok {
		_spec.SetField(conversation.FieldLastMessageSenderType, field.TypeString, value)
		_node.LastMessageSenderType = value
	}
	if value, ok := _c.mutation.LastMessageExcerpt(); ok {
		_spec.SetField(conversation.FieldLastMessageExcerpt, field.TypeString, value)
		_node.LastMessageExcerpt = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(conversation.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = value
	}
	if value, ok := _c.mutation.UserLastReadMessageID(); ok {
		_spec.SetField(conversation.FieldUserLastReadMessageID, field.TypeInt64, value)
		_node.UserLastReadMessageID = &value
	}
	if value, ok := _c.mutation.UserLastReadAt(); ok {
		_spec.SetField(conversation.FieldUserLastReadAt, field.TypeTime, value)
		_node.UserLastReadAt = &value
	}
	if value, ok := _c.mutation.AdminLastReadMessageID(); ok {
		_spec.SetField(conversation.FieldAdminLastReadMessageID, field.TypeInt64, value)
		_node.AdminLastReadMessageID = &value
	}
	if value, ok := _c.mutation.AdminLastReadAt(); ok {
		_spec.SetField(conversation.FieldAdminLastReadAt, field.TypeTime, value)
		_node.AdminLastReadAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.UserTable,
			Columns: []string{conversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignedAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.AssignedAdminTable,
			Columns: []string{conversation.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssignedAdminID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReferencedNoticeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.ReferencedNoticeTable,
			Columns: []string{conversation.ReferencedNoticeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReferencedNoticeID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReferencedByConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ReferencedByConversationsTable,
			Columns: []string{conversation.ReferencedByConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Conversation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationCreate) OnConflict(opts ...sql.ConflictOption) *ConversationUpsertOne {
	_c.conflict = opts
	return &ConversationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationCreate) OnConflictColumns(columns ...string) *ConversationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationUpsertOne{
		create: _c,
	}
}

type (
	// ConversationUpsertOne is the builder for "upsert"-ing
	//  one Conversation node.
	ConversationUpsertOne struct {
		create *ConversationCreate
	}

	// ConversationUpsert is the "OnConflict" setter.
	ConversationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ConversationUpsert) SetUpdatedAt(v time.Time) *ConversationUpsert {
	u.Set(conversation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateUpdatedAt() *ConversationUpsert {
	u.SetExcluded(conversation.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ConversationUpsert) SetUserID(v int64) *ConversationUpsert {
	u.Set(conversation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateUserID() *ConversationUpsert {
	u.SetExcluded(conversation.FieldUserID)
	return u
}

// SetSubject sets the "subject" field.
func (u *ConversationUpsert) SetSubject(v string) *ConversationUpsert {
	u.Set(conversation.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateSubject() *ConversationUpsert {
	u.SetExcluded(conversation.FieldSubject)
	return u
}

// SetStatus sets the "status" field.
func (u *ConversationUpsert) SetStatus(v string) *ConversationUpsert {
	u.Set(conversation.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateStatus() *ConversationUpsert {
	u.SetExcluded(conversation.FieldStatus)
	return u
}

// SetKind sets the "kind" field.
func (u *ConversationUpsert) SetKind(v string) *ConversationUpsert {
	u.Set(conversation.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateKind() *ConversationUpsert {
	u.SetExcluded(conversation.FieldKind)
	return u
}

// SetPriority sets the "priority" field.
func (u *ConversationUpsert) SetPriority(v string) *ConversationUpsert {
	u.Set(conversation.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ConversationUpsert) UpdatePriority() *ConversationUpsert {
	u.SetExcluded(conversation.FieldPriority)
	return u
}

// SetType sets the "type" field.
func (u *ConversationUpsert) SetType(v string) *ConversationUpsert {
	u.Set(conversation.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateType() *ConversationUpsert {
	u.SetExcluded(conversation.FieldType)
	return u
}

// SetSource sets the "source" field.
func (u *ConversationUpsert) SetSource(v string) *ConversationUpsert {
	u.Set(conversation.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateSource() *ConversationUpsert {
	u.SetExcluded(conversation.FieldSource)
	return u
}

// SetSourceID sets the "source_id" field.
func (u *ConversationUpsert) SetSourceID(v string) *ConversationUpsert {
	u.Set(conversation.FieldSourceID, v)
	return u
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateSourceID() *ConversationUpsert {
	u.SetExcluded(conversation.FieldSourceID)
	return u
}

// SetReferencedNoticeID sets the "referenced_notice_id" field.
func (u *ConversationUpsert) SetReferencedNoticeID(v int64) *ConversationUpsert {
	u.Set(conversation.FieldReferencedNoticeID, v)
	return u
}

// UpdateReferencedNoticeID sets the "referenced_notice_id" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateReferencedNoticeID() *ConversationUpsert {
	u.SetExcluded(conversation.FieldReferencedNoticeID)
	return u
}

// ClearReferencedNoticeID clears the value of the "referenced_notice_id" field.
func (u *ConversationUpsert) ClearReferencedNoticeID() *ConversationUpsert {
	u.SetNull(conversation.FieldReferencedNoticeID)
	return u
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (u *ConversationUpsert) SetAssignedAdminID(v int64) *ConversationUpsert {
	u.Set(conversation.FieldAssignedAdminID, v)
	return u
}

// UpdateAssignedAdminID sets the "assigned_admin_id" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateAssignedAdminID() *ConversationUpsert {
	u.SetExcluded(conversation.FieldAssignedAdminID)
	return u
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (u *ConversationUpsert) ClearAssignedAdminID() *ConversationUpsert {
	u.SetNull(conversation.FieldAssignedAdminID)
	return u
}

// SetLastMessageID sets the "last_message_id" field.
func (u *ConversationUpsert) SetLastMessageID(v int64) *ConversationUpsert {
	u.Set(conversation.FieldLastMessageID, v)
	return u
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateLastMessageID() *ConversationUpsert {
	u.SetExcluded(conversation.FieldLastMessageID)
	return u
}

// AddLastMessageID adds v to the "last_message_id" field.
func (u *ConversationUpsert) AddLastMessageID(v int64) *ConversationUpsert {
	u.Add(conversation.FieldLastMessageID, v)
	return u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *ConversationUpsert) ClearLastMessageID() *ConversationUpsert {
	u.SetNull(conversation.FieldLastMessageID)
	return u
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (u *ConversationUpsert) SetLastMessageSenderType(v string) *ConversationUpsert {
	u.Set(conversation.FieldLastMessageSenderType, v)
	return u
}

// UpdateLastMessageSenderType sets the "last_message_sender_type" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateLastMessageSenderType() *ConversationUpsert {
	u.SetExcluded(conversation.FieldLastMessageSenderType)
	return u
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (u *ConversationUpsert) SetLastMessageExcerpt(v string) *ConversationUpsert {
	u.Set(conversation.FieldLastMessageExcerpt, v)
	return u
}

// UpdateLastMessageExcerpt sets the "last_message_excerpt" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateLastMessageExcerpt() *ConversationUpsert {
	u.SetExcluded(conversation.FieldLastMessageExcerpt)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ConversationUpsert) SetLastMessageAt(v time.Time) *ConversationUpsert {
	u.Set(conversation.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateLastMessageAt() *ConversationUpsert {
	u.SetExcluded(conversation.FieldLastMessageAt)
	return u
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (u *ConversationUpsert) SetUserLastReadMessageID(v int64) *ConversationUpsert {
	u.Set(conversation.FieldUserLastReadMessageID, v)
	return u
}

// UpdateUserLastReadMessageID sets the "user_last_read_message_id" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateUserLastReadMessageID() *ConversationUpsert {
	u.SetExcluded(conversation.FieldUserLastReadMessageID)
	return u
}

// AddUserLastReadMessageID adds v to the "user_last_read_message_id" field.
func (u *ConversationUpsert) AddUserLastReadMessageID(v int64) *ConversationUpsert {
	u.Add(conversation.FieldUserLastReadMessageID, v)
	return u
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (u *ConversationUpsert) ClearUserLastReadMessageID() *ConversationUpsert {
	u.SetNull(conversation.FieldUserLastReadMessageID)
	return u
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (u *ConversationUpsert) SetUserLastReadAt(v time.Time) *ConversationUpsert {
	u.Set(conversation.FieldUserLastReadAt, v)
	return u
}

// UpdateUserLastReadAt sets the "user_last_read_at" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateUserLastReadAt() *ConversationUpsert {
	u.SetExcluded(conversation.FieldUserLastReadAt)
	return u
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (u *ConversationUpsert) ClearUserLastReadAt() *ConversationUpsert {
	u.SetNull(conversation.FieldUserLastReadAt)
	return u
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (u *ConversationUpsert) SetAdminLastReadMessageID(v int64) *ConversationUpsert {
	u.Set(conversation.FieldAdminLastReadMessageID, v)
	return u
}

// UpdateAdminLastReadMessageID sets the "admin_last_read_message_id" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateAdminLastReadMessageID() *ConversationUpsert {
	u.SetExcluded(conversation.FieldAdminLastReadMessageID)
	return u
}

// AddAdminLastReadMessageID adds v to the "admin_last_read_message_id" field.
func (u *ConversationUpsert) AddAdminLastReadMessageID(v int64) *ConversationUpsert {
	u.Add(conversation.FieldAdminLastReadMessageID, v)
	return u
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (u *ConversationUpsert) ClearAdminLastReadMessageID() *ConversationUpsert {
	u.SetNull(conversation.FieldAdminLastReadMessageID)
	return u
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (u *ConversationUpsert) SetAdminLastReadAt(v time.Time) *ConversationUpsert {
	u.Set(conversation.FieldAdminLastReadAt, v)
	return u
}

// UpdateAdminLastReadAt sets the "admin_last_read_at" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateAdminLastReadAt() *ConversationUpsert {
	u.SetExcluded(conversation.FieldAdminLastReadAt)
	return u
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (u *ConversationUpsert) ClearAdminLastReadAt() *ConversationUpsert {
	u.SetNull(conversation.FieldAdminLastReadAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationUpsertOne) UpdateNewValues() *ConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(conversation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Conversation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConversationUpsertOne) Ignore() *ConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationUpsertOne) DoNothing() *ConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationCreate.OnConflict
// documentation for more info.
func (u *ConversationUpsertOne) Update(set func(*ConversationUpsert)) *ConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConversationUpsertOne) SetUpdatedAt(v time.Time) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateUpdatedAt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ConversationUpsertOne) SetUserID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateUserID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetSubject sets the "subject" field.
func (u *ConversationUpsertOne) SetSubject(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateSubject() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateSubject()
	})
}

// SetStatus sets the "status" field.
func (u *ConversationUpsertOne) SetStatus(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateStatus() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateStatus()
	})
}

// SetKind sets the "kind" field.
func (u *ConversationUpsertOne) SetKind(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateKind() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateKind()
	})
}

// SetPriority sets the "priority" field.
func (u *ConversationUpsertOne) SetPriority(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdatePriority() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdatePriority()
	})
}

// SetType sets the "type" field.
func (u *ConversationUpsertOne) SetType(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateType() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateType()
	})
}

// SetSource sets the "source" field.
func (u *ConversationUpsertOne) SetSource(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateSource() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateSource()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ConversationUpsertOne) SetSourceID(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateSourceID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateSourceID()
	})
}

// SetReferencedNoticeID sets the "referenced_notice_id" field.
func (u *ConversationUpsertOne) SetReferencedNoticeID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetReferencedNoticeID(v)
	})
}

// UpdateReferencedNoticeID sets the "referenced_notice_id" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateReferencedNoticeID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateReferencedNoticeID()
	})
}

// ClearReferencedNoticeID clears the value of the "referenced_notice_id" field.
func (u *ConversationUpsertOne) ClearReferencedNoticeID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearReferencedNoticeID()
	})
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (u *ConversationUpsertOne) SetAssignedAdminID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetAssignedAdminID(v)
	})
}

// UpdateAssignedAdminID sets the "assigned_admin_id" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateAssignedAdminID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateAssignedAdminID()
	})
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (u *ConversationUpsertOne) ClearAssignedAdminID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearAssignedAdminID()
	})
}

// SetLastMessageID sets the "last_message_id" field.
func (u *ConversationUpsertOne) SetLastMessageID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetLastMessageID(v)
	})
}

// AddLastMessageID adds v to the "last_message_id" field.
func (u *ConversationUpsertOne) AddLastMessageID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.AddLastMessageID(v)
	})
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateLastMessageID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateLastMessageID()
	})
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *ConversationUpsertOne) ClearLastMessageID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearLastMessageID()
	})
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (u *ConversationUpsertOne) SetLastMessageSenderType(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetLastMessageSenderType(v)
	})
}

// UpdateLastMessageSenderType sets the "last_message_sender_type" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateLastMessageSenderType() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateLastMessageSenderType()
	})
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (u *ConversationUpsertOne) SetLastMessageExcerpt(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetLastMessageExcerpt(v)
	})
}

// UpdateLastMessageExcerpt sets the "last_message_excerpt" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateLastMessageExcerpt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateLastMessageExcerpt()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ConversationUpsertOne) SetLastMessageAt(v time.Time) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateLastMessageAt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (u *ConversationUpsertOne) SetUserLastReadMessageID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUserLastReadMessageID(v)
	})
}

// AddUserLastReadMessageID adds v to the "user_last_read_message_id" field.
func (u *ConversationUpsertOne) AddUserLastReadMessageID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.AddUserLastReadMessageID(v)
	})
}

// UpdateUserLastReadMessageID sets the "user_last_read_message_id" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateUserLastReadMessageID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUserLastReadMessageID()
	})
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (u *ConversationUpsertOne) ClearUserLastReadMessageID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearUserLastReadMessageID()
	})
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (u *ConversationUpsertOne) SetUserLastReadAt(v time.Time) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUserLastReadAt(v)
	})
}

// UpdateUserLastReadAt sets the "user_last_read_at" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateUserLastReadAt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUserLastReadAt()
	})
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (u *ConversationUpsertOne) ClearUserLastReadAt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearUserLastReadAt()
	})
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (u *ConversationUpsertOne) SetAdminLastReadMessageID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetAdminLastReadMessageID(v)
	})
}

// AddAdminLastReadMessageID adds v to the "admin_last_read_message_id" field.
func (u *ConversationUpsertOne) AddAdminLastReadMessageID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.AddAdminLastReadMessageID(v)
	})
}

// UpdateAdminLastReadMessageID sets the "admin_last_read_message_id" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateAdminLastReadMessageID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateAdminLastReadMessageID()
	})
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (u *ConversationUpsertOne) ClearAdminLastReadMessageID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearAdminLastReadMessageID()
	})
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (u *ConversationUpsertOne) SetAdminLastReadAt(v time.Time) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetAdminLastReadAt(v)
	})
}

// UpdateAdminLastReadAt sets the "admin_last_read_at" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateAdminLastReadAt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateAdminLastReadAt()
	})
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (u *ConversationUpsertOne) ClearAdminLastReadAt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearAdminLastReadAt()
	})
}

// Exec executes the query.
func (u *ConversationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConversationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConversationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConversationCreateBulk is the builder for creating many Conversation entities in bulk.
type ConversationCreateBulk struct {
	config
	err      error
	builders []*ConversationCreate
	conflict []sql.ConflictOption
}

// Save creates the Conversation entities in the database.
func (_c *ConversationCreateBulk) Save(ctx context.Context) ([]*Conversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Conversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationCreateBulk) SaveX(ctx context.Context) []*Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Conversation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConversationUpsertBulk {
	_c.conflict = opts
	return &ConversationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationCreateBulk) OnConflictColumns(columns ...string) *ConversationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationUpsertBulk{
		create: _c,
	}
}

// ConversationUpsertBulk is the builder for "upsert"-ing
// a bulk of Conversation nodes.
type ConversationUpsertBulk struct {
	create *ConversationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationUpsertBulk) UpdateNewValues() *ConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(conversation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConversationUpsertBulk) Ignore() *ConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationUpsertBulk) DoNothing() *ConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationCreateBulk.OnConflict
// documentation for more info.
func (u *ConversationUpsertBulk) Update(set func(*ConversationUpsert)) *ConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConversationUpsertBulk) SetUpdatedAt(v time.Time) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateUpdatedAt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ConversationUpsertBulk) SetUserID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateUserID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetSubject sets the "subject" field.
func (u *ConversationUpsertBulk) SetSubject(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateSubject() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateSubject()
	})
}

// SetStatus sets the "status" field.
func (u *ConversationUpsertBulk) SetStatus(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateStatus() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateStatus()
	})
}

// SetKind sets the "kind" field.
func (u *ConversationUpsertBulk) SetKind(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateKind() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateKind()
	})
}

// SetPriority sets the "priority" field.
func (u *ConversationUpsertBulk) SetPriority(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdatePriority() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdatePriority()
	})
}

// SetType sets the "type" field.
func (u *ConversationUpsertBulk) SetType(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateType() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateType()
	})
}

// SetSource sets the "source" field.
func (u *ConversationUpsertBulk) SetSource(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateSource() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateSource()
	})
}

// SetSourceID sets the "source_id" field.
func (u *ConversationUpsertBulk) SetSourceID(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetSourceID(v)
	})
}

// UpdateSourceID sets the "source_id" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateSourceID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateSourceID()
	})
}

// SetReferencedNoticeID sets the "referenced_notice_id" field.
func (u *ConversationUpsertBulk) SetReferencedNoticeID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetReferencedNoticeID(v)
	})
}

// UpdateReferencedNoticeID sets the "referenced_notice_id" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateReferencedNoticeID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateReferencedNoticeID()
	})
}

// ClearReferencedNoticeID clears the value of the "referenced_notice_id" field.
func (u *ConversationUpsertBulk) ClearReferencedNoticeID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearReferencedNoticeID()
	})
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (u *ConversationUpsertBulk) SetAssignedAdminID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetAssignedAdminID(v)
	})
}

// UpdateAssignedAdminID sets the "assigned_admin_id" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateAssignedAdminID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateAssignedAdminID()
	})
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (u *ConversationUpsertBulk) ClearAssignedAdminID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearAssignedAdminID()
	})
}

// SetLastMessageID sets the "last_message_id" field.
func (u *ConversationUpsertBulk) SetLastMessageID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetLastMessageID(v)
	})
}

// AddLastMessageID adds v to the "last_message_id" field.
func (u *ConversationUpsertBulk) AddLastMessageID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.AddLastMessageID(v)
	})
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateLastMessageID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateLastMessageID()
	})
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *ConversationUpsertBulk) ClearLastMessageID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearLastMessageID()
	})
}

// SetLastMessageSenderType sets the "last_message_sender_type" field.
func (u *ConversationUpsertBulk) SetLastMessageSenderType(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetLastMessageSenderType(v)
	})
}

// UpdateLastMessageSenderType sets the "last_message_sender_type" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateLastMessageSenderType() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateLastMessageSenderType()
	})
}

// SetLastMessageExcerpt sets the "last_message_excerpt" field.
func (u *ConversationUpsertBulk) SetLastMessageExcerpt(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetLastMessageExcerpt(v)
	})
}

// UpdateLastMessageExcerpt sets the "last_message_excerpt" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateLastMessageExcerpt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateLastMessageExcerpt()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *ConversationUpsertBulk) SetLastMessageAt(v time.Time) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateLastMessageAt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateLastMessageAt()
	})
}

// SetUserLastReadMessageID sets the "user_last_read_message_id" field.
func (u *ConversationUpsertBulk) SetUserLastReadMessageID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUserLastReadMessageID(v)
	})
}

// AddUserLastReadMessageID adds v to the "user_last_read_message_id" field.
func (u *ConversationUpsertBulk) AddUserLastReadMessageID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.AddUserLastReadMessageID(v)
	})
}

// UpdateUserLastReadMessageID sets the "user_last_read_message_id" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateUserLastReadMessageID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUserLastReadMessageID()
	})
}

// ClearUserLastReadMessageID clears the value of the "user_last_read_message_id" field.
func (u *ConversationUpsertBulk) ClearUserLastReadMessageID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearUserLastReadMessageID()
	})
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (u *ConversationUpsertBulk) SetUserLastReadAt(v time.Time) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUserLastReadAt(v)
	})
}

// UpdateUserLastReadAt sets the "user_last_read_at" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateUserLastReadAt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUserLastReadAt()
	})
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (u *ConversationUpsertBulk) ClearUserLastReadAt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearUserLastReadAt()
	})
}

// SetAdminLastReadMessageID sets the "admin_last_read_message_id" field.
func (u *ConversationUpsertBulk) SetAdminLastReadMessageID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetAdminLastReadMessageID(v)
	})
}

// AddAdminLastReadMessageID adds v to the "admin_last_read_message_id" field.
func (u *ConversationUpsertBulk) AddAdminLastReadMessageID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.AddAdminLastReadMessageID(v)
	})
}

// UpdateAdminLastReadMessageID sets the "admin_last_read_message_id" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateAdminLastReadMessageID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateAdminLastReadMessageID()
	})
}

// ClearAdminLastReadMessageID clears the value of the "admin_last_read_message_id" field.
func (u *ConversationUpsertBulk) ClearAdminLastReadMessageID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearAdminLastReadMessageID()
	})
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (u *ConversationUpsertBulk) SetAdminLastReadAt(v time.Time) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetAdminLastReadAt(v)
	})
}

// UpdateAdminLastReadAt sets the "admin_last_read_at" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateAdminLastReadAt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateAdminLastReadAt()
	})
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (u *ConversationUpsertBulk) ClearAdminLastReadAt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearAdminLastReadAt()
	})
}

// Exec executes the query.
func (u *ConversationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConversationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
