// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ConversationMessageUpdate is the builder for updating ConversationMessage entities.
type ConversationMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationMessageMutation
}

// Where appends a list predicates to the ConversationMessageUpdate builder.
func (_u *ConversationMessageUpdate) Where(ps ...predicate.ConversationMessage) *ConversationMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ConversationMessageUpdate) SetConversationID(v int64) *ConversationMessageUpdate {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableConversationID(v *int64) *ConversationMessageUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *ConversationMessageUpdate) SetSenderType(v string) *ConversationMessageUpdate {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableSenderType(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *ConversationMessageUpdate) SetSenderID(v int64) *ConversationMessageUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableSenderID(v *int64) *ConversationMessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *ConversationMessageUpdate) ClearSenderID() *ConversationMessageUpdate {
	_u.mutation.ClearSenderID()
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *ConversationMessageUpdate) SetMessageType(v string) *ConversationMessageUpdate {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableMessageType(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetContentFormat sets the "content_format" field.
func (_u *ConversationMessageUpdate) SetContentFormat(v string) *ConversationMessageUpdate {
	_u.mutation.SetContentFormat(v)
	return _u
}

// SetNillableContentFormat sets the "content_format" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableContentFormat(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetContentFormat(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ConversationMessageUpdate) SetContent(v string) *ConversationMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableContent(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ConversationMessageUpdate) SetMetadata(v map[string]interface{}) *ConversationMessageUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ConversationMessageUpdate) ClearMetadata() *ConversationMessageUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdate) SetConversation(v *Conversation) *ConversationMessageUpdate {
	return _u.SetConversationID(v.ID)
}

// SetSender sets the "sender" edge to the User entity.
func (_u *ConversationMessageUpdate) SetSender(v *User) *ConversationMessageUpdate {
	return _u.SetSenderID(v.ID)
}

// Mutation returns the ConversationMessageMutation object of the builder.
func (_u *ConversationMessageUpdate) Mutation() *ConversationMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdate) ClearConversation() *ConversationMessageUpdate {
	_u.mutation.ClearConversation()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *ConversationMessageUpdate) ClearSender() *ConversationMessageUpdate {
	_u.mutation.ClearSender()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationMessageUpdate) check() error {
	if v, ok := _u.mutation.SenderType(); ok {
		if err := conversationmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageType(); ok {
		if err := conversationmessage.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.message_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentFormat(); ok {
		if err := conversationmessage.ContentFormatValidator(v); err != nil {
			return &ValidationError{Name: "content_format", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.content_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := conversationmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.content": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.conversation"`)
	}
	return nil
}

func (_u *ConversationMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationmessage.Table, conversationmessage.Columns, sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(conversationmessage.FieldSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(conversationmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentFormat(); ok {
		_spec.SetField(conversationmessage.FieldContentFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(conversationmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(conversationmessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(conversationmessage.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.SenderTable,
			Columns: []string{conversationmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.SenderTable,
			Columns: []string{conversationmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationMessageUpdateOne is the builder for updating a single ConversationMessage entity.
type ConversationMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationMessageMutation
}

// SetConversationID sets the "conversation_id" field.
func (_u *ConversationMessageUpdateOne) SetConversationID(v int64) *ConversationMessageUpdateOne {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableConversationID(v *int64) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetSenderType sets the "sender_type" field.
func (_u *ConversationMessageUpdateOne) SetSenderType(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetSenderType(v)
	return _u
}

// SetNillableSenderType sets the "sender_type" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableSenderType(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetSenderType(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *ConversationMessageUpdateOne) SetSenderID(v int64) *ConversationMessageUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableSenderID(v *int64) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *ConversationMessageUpdateOne) ClearSenderID() *ConversationMessageUpdateOne {
	_u.mutation.ClearSenderID()
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *ConversationMessageUpdateOne) SetMessageType(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableMessageType(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetContentFormat sets the "content_format" field.
func (_u *ConversationMessageUpdateOne) SetContentFormat(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetContentFormat(v)
	return _u
}

// SetNillableContentFormat sets the "content_format" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableContentFormat(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetContentFormat(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ConversationMessageUpdateOne) SetContent(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableContent(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ConversationMessageUpdateOne) SetMetadata(v map[string]interface{}) *ConversationMessageUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ConversationMessageUpdateOne) ClearMetadata() *ConversationMessageUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdateOne) SetConversation(v *Conversation) *ConversationMessageUpdateOne {
	return _u.SetConversationID(v.ID)
}

// SetSender sets the "sender" edge to the User entity.
func (_u *ConversationMessageUpdateOne) SetSender(v *User) *ConversationMessageUpdateOne {
	return _u.SetSenderID(v.ID)
}

// Mutation returns the ConversationMessageMutation object of the builder.
func (_u *ConversationMessageUpdateOne) Mutation() *ConversationMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdateOne) ClearConversation() *ConversationMessageUpdateOne {
	_u.mutation.ClearConversation()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *ConversationMessageUpdateOne) ClearSender() *ConversationMessageUpdateOne {
	_u.mutation.ClearSender()
	return _u
}

// Where appends a list predicates to the ConversationMessageUpdate builder.
func (_u *ConversationMessageUpdateOne) Where(ps ...predicate.ConversationMessage) *ConversationMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationMessageUpdateOne) Select(field string, fields ...string) *ConversationMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConversationMessage entity.
func (_u *ConversationMessageUpdateOne) Save(ctx context.Context) (*ConversationMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationMessageUpdateOne) SaveX(ctx context.Context) *ConversationMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationMessageUpdateOne) check() error {
	if v, ok := _u.mutation.SenderType(); ok {
		if err := conversationmessage.SenderTypeValidator(v); err != nil {
			return &ValidationError{Name: "sender_type", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.sender_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageType(); ok {
		if err := conversationmessage.MessageTypeValidator(v); err != nil {
			return &ValidationError{Name: "message_type", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.message_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentFormat(); ok {
		if err := conversationmessage.ContentFormatValidator(v); err != nil {
			return &ValidationError{Name: "content_format", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.content_format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := conversationmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.content": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.conversation"`)
	}
	return nil
}

func (_u *ConversationMessageUpdateOne) sqlSave(ctx context.Context) (_node *ConversationMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationmessage.Table, conversationmessage.Columns, sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConversationMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversationmessage.FieldID)
		for _, f := range fields {
			if !conversationmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversationmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SenderType(); ok {
		_spec.SetField(conversationmessage.FieldSenderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(conversationmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentFormat(); ok {
		_spec.SetField(conversationmessage.FieldContentFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(conversationmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(conversationmessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(conversationmessage.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.SenderTable,
			Columns: []string{conversationmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.SenderTable,
			Columns: []string{conversationmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ConversationMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
