// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/conversationmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ConversationMessage is the model entity for the ConversationMessage schema.
type ConversationMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 会话 ID
	ConversationID int64 `json:"conversation_id,omitempty"`
	// 发送方: user, admin, system
	SenderType string `json:"sender_type,omitempty"`
	// 发送方用户 ID，系统消息为空
	SenderID *int64 `json:"sender_id,omitempty"`
	// 消息类型: text, notice, operation_log, system_event
	MessageType string `json:"message_type,omitempty"`
	// 内容格式: plain, markdown
	ContentFormat string `json:"content_format,omitempty"`
	// 消息内容
	Content string `json:"content,omitempty"`
	// 消息元数据
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConversationMessageQuery when eager-loading is set.
	Edges        ConversationMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConversationMessageEdges holds the relations/edges for other nodes in the graph.
type ConversationMessageEdges struct {
	// Conversation holds the value of the conversation edge.
	Conversation *Conversation `json:"conversation,omitempty"`
	// Sender holds the value of the sender edge.
	Sender *User `json:"sender,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ConversationOrErr returns the Conversation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationMessageEdges) ConversationOrErr() (*Conversation, error) {
	if e.Conversation != nil {
		return e.Conversation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: conversation.Label}
	}
	return nil, &NotLoadedError{edge: "conversation"}
}

// SenderOrErr returns the Sender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationMessageEdges) SenderOrErr() (*User, error) {
	if e.Sender != nil {
		return e.Sender, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "sender"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConversationMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conversationmessage.FieldMetadata:
			values[i] = new([]byte)
		case conversationmessage.FieldID, conversationmessage.FieldConversationID, conversationmessage.FieldSenderID:
			values[i] = new(sql.NullInt64)
		case conversationmessage.FieldSenderType, conversationmessage.FieldMessageType, conversationmessage.FieldContentFormat, conversationmessage.FieldContent:
			values[i] = new(sql.NullString)
		case conversationmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConversationMessage fields.
func (_m *ConversationMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conversationmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case conversationmessage.FieldConversationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_id", values[i])
			} else if value.Valid {
				_m.ConversationID = value.Int64
			}
		case conversationmessage.FieldSenderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_type", values[i])
			} else if value.Valid {
				_m.SenderType = value.String
			}
		case conversationmessage.FieldSenderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sender_id", values[i])
			} else if value.Valid {
				_m.SenderID = new(int64)
				*_m.SenderID = value.Int64
			}
		case conversationmessage.FieldMessageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_type", values[i])
			} else if value.Valid {
				_m.MessageType = value.String
			}
		case conversationmessage.FieldContentFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_format", values[i])
			} else if value.Valid {
				_m.ContentFormat = value.String
			}
		case conversationmessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case conversationmessage.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case conversationmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConversationMessage.
// This includes values selected through modifiers, order, etc.
func (_m *ConversationMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConversation queries the "conversation" edge of the ConversationMessage entity.
func (_m *ConversationMessage) QueryConversation() *ConversationQuery {
	return NewConversationMessageClient(_m.config).QueryConversation(_m)
}

// QuerySender queries the "sender" edge of the ConversationMessage entity.
func (_m *ConversationMessage) QuerySender() *UserQuery {
	return NewConversationMessageClient(_m.config).QuerySender(_m)
}

// Update returns a builder for updating this ConversationMessage.
// Note that you need to call ConversationMessage.Unwrap() before calling this method if this ConversationMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConversationMessage) Update() *ConversationMessageUpdateOne {
	return NewConversationMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConversationMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConversationMessage) Unwrap() *ConversationMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConversationMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConversationMessage) String() string {
	var builder strings.Builder
	builder.WriteString("ConversationMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("conversation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConversationID))
	builder.WriteString(", ")
	builder.WriteString("sender_type=")
	builder.WriteString(_m.SenderType)
	builder.WriteString(", ")
	if v := _m.SenderID; v != nil {
		builder.WriteString("sender_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("message_type=")
	builder.WriteString(_m.MessageType)
	builder.WriteString(", ")
	builder.WriteString("content_format=")
	builder.WriteString(_m.ContentFormat)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ConversationMessages is a parsable slice of ConversationMessage.
type ConversationMessages []*ConversationMessage
