// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// Conversation is the model entity for the Conversation schema.
type Conversation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 会话所属用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 会话主题
	Subject string `json:"subject,omitempty"`
	// 状态: open, pending_user, pending_admin, resolved, closed
	Status string `json:"status,omitempty"`
	// 会话形态: ticket, system_notice
	Kind string `json:"kind,omitempty"`
	// 优先级: low, normal, high, urgent
	Priority string `json:"priority,omitempty"`
	// 类型: support, notice, billing, subscription, account, security
	Type string `json:"type,omitempty"`
	// 来源模块，可为空
	Source string `json:"source,omitempty"`
	// 来源业务对象 ID，可为空
	SourceID string `json:"source_id,omitempty"`
	// 工单引用的系统通知 ID
	ReferencedNoticeID *int64 `json:"referenced_notice_id,omitempty"`
	// 负责人管理员 ID
	AssignedAdminID *int64 `json:"assigned_admin_id,omitempty"`
	// 最后一条消息 ID
	LastMessageID *int64 `json:"last_message_id,omitempty"`
	// 最后一条消息发送方
	LastMessageSenderType string `json:"last_message_sender_type,omitempty"`
	// 最后一条消息摘要
	LastMessageExcerpt string `json:"last_message_excerpt,omitempty"`
	// 最后消息时间
	LastMessageAt time.Time `json:"last_message_at,omitempty"`
	// 用户最后已读消息 ID
	UserLastReadMessageID *int64 `json:"user_last_read_message_id,omitempty"`
	// 用户最后已读时间
	UserLastReadAt *time.Time `json:"user_last_read_at,omitempty"`
	// 管理员侧最后已读消息 ID
	AdminLastReadMessageID *int64 `json:"admin_last_read_message_id,omitempty"`
	// 管理员侧最后已读时间
	AdminLastReadAt *time.Time `json:"admin_last_read_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConversationQuery when eager-loading is set.
	Edges        ConversationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConversationEdges holds the relations/edges for other nodes in the graph.
type ConversationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// AssignedAdmin holds the value of the assigned_admin edge.
	AssignedAdmin *User `json:"assigned_admin,omitempty"`
	// ReferencedNotice holds the value of the referenced_notice edge.
	ReferencedNotice *Conversation `json:"referenced_notice,omitempty"`
	// ReferencedByConversations holds the value of the referenced_by_conversations edge.
	ReferencedByConversations []*Conversation `json:"referenced_by_conversations,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*ConversationMessage `json:"messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AssignedAdminOrErr returns the AssignedAdmin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationEdges) AssignedAdminOrErr() (*User, error) {
	if e.AssignedAdmin != nil {
		return e.AssignedAdmin, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assigned_admin"}
}

// ReferencedNoticeOrErr returns the ReferencedNotice value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationEdges) ReferencedNoticeOrErr() (*Conversation, error) {
	if e.ReferencedNotice != nil {
		return e.ReferencedNotice, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: conversation.Label}
	}
	return nil, &NotLoadedError{edge: "referenced_notice"}
}

// ReferencedByConversationsOrErr returns the ReferencedByConversations value or an error if the edge
// was not loaded in eager-loading.
func (e ConversationEdges) ReferencedByConversationsOrErr() ([]*Conversation, error) {
	if e.loadedTypes[3] {
		return e.ReferencedByConversations, nil
	}
	return nil, &NotLoadedError{edge: "referenced_by_conversations"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e ConversationEdges) MessagesOrErr() ([]*ConversationMessage, error) {
	if e.loadedTypes[4] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Conversation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conversation.FieldID, conversation.FieldUserID, conversation.FieldReferencedNoticeID, conversation.FieldAssignedAdminID, conversation.FieldLastMessageID, conversation.FieldUserLastReadMessageID, conversation.FieldAdminLastReadMessageID:
			values[i] = new(sql.NullInt64)
		case conversation.FieldSubject, conversation.FieldStatus, conversation.FieldKind, conversation.FieldPriority, conversation.FieldType, conversation.FieldSource, conversation.FieldSourceID, conversation.FieldLastMessageSenderType, conversation.FieldLastMessageExcerpt:
			values[i] = new(sql.NullString)
		case conversation.FieldCreatedAt, conversation.FieldUpdatedAt, conversation.FieldLastMessageAt, conversation.FieldUserLastReadAt, conversation.FieldAdminLastReadAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Conversation fields.
func (_m *Conversation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conversation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case conversation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case conversation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case conversation.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case conversation.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case conversation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case conversation.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case conversation.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case conversation.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case conversation.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case conversation.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case conversation.FieldReferencedNoticeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referenced_notice_id", values[i])
			} else if value.Valid {
				_m.ReferencedNoticeID = new(int64)
				*_m.ReferencedNoticeID = value.Int64
			}
		case conversation.FieldAssignedAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_admin_id", values[i])
			} else if value.Valid {
				_m.AssignedAdminID = new(int64)
				*_m.AssignedAdminID = value.Int64
			}
		case conversation.FieldLastMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_id", values[i])
			} else if value.Valid {
				_m.LastMessageID = new(int64)
				*_m.LastMessageID = value.Int64
			}
		case conversation.FieldLastMessageSenderType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_sender_type", values[i])
			} else if value.Valid {
				_m.LastMessageSenderType = value.String
			}
		case conversation.FieldLastMessageExcerpt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_excerpt", values[i])
			} else if value.Valid {
				_m.LastMessageExcerpt = value.String
			}
		case conversation.FieldLastMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_at", values[i])
			} else if value.Valid {
				_m.LastMessageAt = value.Time
			}
		case conversation.FieldUserLastReadMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_last_read_message_id", values[i])
			} else if value.Valid {
				_m.UserLastReadMessageID = new(int64)
				*_m.UserLastReadMessageID = value.Int64
			}
		case conversation.FieldUserLastReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field user_last_read_at", values[i])
			} else if value.Valid {
				_m.UserLastReadAt = new(time.Time)
				*_m.UserLastReadAt = value.Time
			}
		case conversation.FieldAdminLastReadMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_last_read_message_id", values[i])
			} else if value.Valid {
				_m.AdminLastReadMessageID = new(int64)
				*_m.AdminLastReadMessageID = value.Int64
			}
		case conversation.FieldAdminLastReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field admin_last_read_at", values[i])
			} else if value.Valid {
				_m.AdminLastReadAt = new(time.Time)
				*_m.AdminLastReadAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Conversation.
// This includes values selected through modifiers, order, etc.
func (_m *Conversation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Conversation entity.
func (_m *Conversation) QueryUser() *UserQuery {
	return NewConversationClient(_m.config).QueryUser(_m)
}

// QueryAssignedAdmin queries the "assigned_admin" edge of the Conversation entity.
func (_m *Conversation) QueryAssignedAdmin() *UserQuery {
	return NewConversationClient(_m.config).QueryAssignedAdmin(_m)
}

// QueryReferencedNotice queries the "referenced_notice" edge of the Conversation entity.
func (_m *Conversation) QueryReferencedNotice() *ConversationQuery {
	return NewConversationClient(_m.config).QueryReferencedNotice(_m)
}

// QueryReferencedByConversations queries the "referenced_by_conversations" edge of the Conversation entity.
func (_m *Conversation) QueryReferencedByConversations() *ConversationQuery {
	return NewConversationClient(_m.config).QueryReferencedByConversations(_m)
}

// QueryMessages queries the "messages" edge of the Conversation entity.
func (_m *Conversation) QueryMessages() *ConversationMessageQuery {
	return NewConversationClient(_m.config).QueryMessages(_m)
}

// Update returns a builder for updating this Conversation.
// Note that you need to call Conversation.Unwrap() before calling this method if this Conversation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Conversation) Update() *ConversationUpdateOne {
	return NewConversationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Conversation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Conversation) Unwrap() *Conversation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Conversation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Conversation) String() string {
	var builder strings.Builder
	builder.WriteString("Conversation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	if v := _m.ReferencedNoticeID; v != nil {
		builder.WriteString("referenced_notice_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AssignedAdminID; v != nil {
		builder.WriteString("assigned_admin_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastMessageID; v != nil {
		builder.WriteString("last_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("last_message_sender_type=")
	builder.WriteString(_m.LastMessageSenderType)
	builder.WriteString(", ")
	builder.WriteString("last_message_excerpt=")
	builder.WriteString(_m.LastMessageExcerpt)
	builder.WriteString(", ")
	builder.WriteString("last_message_at=")
	builder.WriteString(_m.LastMessageAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UserLastReadMessageID; v != nil {
		builder.WriteString("user_last_read_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserLastReadAt; v != nil {
		builder.WriteString("user_last_read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AdminLastReadMessageID; v != nil {
		builder.WriteString("admin_last_read_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AdminLastReadAt; v != nil {
		builder.WriteString("admin_last_read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Conversations is a parsable slice of Conversation.
type Conversations []*Conversation
