// Code generated by ent, DO NOT EDIT.

package shopproduct

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the shopproduct type in the database.
	Label = "shop_product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCoverURL holds the string denoting the cover_url field in the database.
	FieldCoverURL = "cover_url"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldOriginalPrice holds the string denoting the original_price field in the database.
	FieldOriginalPrice = "original_price"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldMinPurchase holds the string denoting the min_purchase field in the database.
	FieldMinPurchase = "min_purchase"
	// FieldMaxPurchase holds the string denoting the max_purchase field in the database.
	FieldMaxPurchase = "max_purchase"
	// FieldAutoDelivery holds the string denoting the auto_delivery field in the database.
	FieldAutoDelivery = "auto_delivery"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeCardKeys holds the string denoting the card_keys edge name in mutations.
	EdgeCardKeys = "card_keys"
	// EdgeOrders holds the string denoting the orders edge name in mutations.
	EdgeOrders = "orders"
	// Table holds the table name of the shopproduct in the database.
	Table = "shop_products"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "shop_products"
	// CategoryInverseTable is the table name for the ShopCategory entity.
	// It exists in this package in order to avoid circular dependency with the "shopcategory" package.
	CategoryInverseTable = "shop_categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_id"
	// CardKeysTable is the table that holds the card_keys relation/edge.
	CardKeysTable = "shop_card_keys"
	// CardKeysInverseTable is the table name for the ShopCardKey entity.
	// It exists in this package in order to avoid circular dependency with the "shopcardkey" package.
	CardKeysInverseTable = "shop_card_keys"
	// CardKeysColumn is the table column denoting the card_keys relation/edge.
	CardKeysColumn = "product_id"
	// OrdersTable is the table that holds the orders relation/edge.
	OrdersTable = "shop_orders"
	// OrdersInverseTable is the table name for the ShopOrder entity.
	// It exists in this package in order to avoid circular dependency with the "shoporder" package.
	OrdersInverseTable = "shop_orders"
	// OrdersColumn is the table column denoting the orders relation/edge.
	OrdersColumn = "product_id"
)

// Columns holds all SQL columns for shopproduct fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCategoryID,
	FieldName,
	FieldCoverURL,
	FieldDescription,
	FieldPrice,
	FieldOriginalPrice,
	FieldEnabled,
	FieldSortOrder,
	FieldMinPurchase,
	FieldMaxPurchase,
	FieldAutoDelivery,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultMinPurchase holds the default value on creation for the "min_purchase" field.
	DefaultMinPurchase int
	// DefaultMaxPurchase holds the default value on creation for the "max_purchase" field.
	DefaultMaxPurchase int
	// DefaultAutoDelivery holds the default value on creation for the "auto_delivery" field.
	DefaultAutoDelivery bool
)

// OrderOption defines the ordering options for the ShopProduct queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCategoryID orders the results by the category_id field.
func ByCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCoverURL orders the results by the cover_url field.
func ByCoverURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverURL, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByOriginalPrice orders the results by the original_price field.
func ByOriginalPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalPrice, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByMinPurchase orders the results by the min_purchase field.
func ByMinPurchase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinPurchase, opts...).ToFunc()
}

// ByMaxPurchase orders the results by the max_purchase field.
func ByMaxPurchase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxPurchase, opts...).ToFunc()
}

// ByAutoDelivery orders the results by the auto_delivery field.
func ByAutoDelivery(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoDelivery, opts...).ToFunc()
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByCardKeysCount orders the results by card_keys count.
func ByCardKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCardKeysStep(), opts...)
	}
}

// ByCardKeys orders the results by card_keys terms.
func ByCardKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCardKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOrdersCount orders the results by orders count.
func ByOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrdersStep(), opts...)
	}
}

// ByOrders orders the results by orders terms.
func ByOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
func newCardKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CardKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CardKeysTable, CardKeysColumn),
	)
}
func newOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrdersTable, OrdersColumn),
	)
}
